"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, Loader2, Sparkles, WandSparkles, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Field } from "@/components/ui/field";
import { Input, Select, Textarea } from "@/components/ui/input";
import { analysisService } from "@/services/analysis-service";
import { WizardShell } from "./wizard-shell";

type Clarification={key:string;question:string;input_type:"NUMBER"|"SELECT"|"TEXT";required_for_confidence:boolean;options?:string[]};
const example="I want to build a food delivery platform for local restaurants with customers, drivers, online payments and live order tracking.";
const features=["Login","Payments","Uploads","Video","Chat","Maps","Notifications","Bookings","Analytics","Subscriptions","APIs","Real-time Tracking"];

export function IdeaWizard(){
  const router=useRouter();
  const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [clarifying,setClarifying]=useState(false);
  const [idea,setIdea]=useState("");const [industry,setIndustry]=useState("Food");const [users,setUsers]=useState("Consumers and local businesses");
  const [chosen,setChosen]=useState<string[]>(["Login","Payments","Maps","Notifications","Real-time Tracking"]);const [traffic,setTraffic]=useState("Growing business");
  const [budget,setBudget]=useState("100");const [timeline,setTimeline]=useState("3–6 months");const [experience,setExperience]=useState("Intermediate");
  const [answers,setAnswers]=useState<Record<string,string>>({});const [questions,setQuestions]=useState<Clarification[]>([]);
  const context=()=>({idea,industry,targetUsers:users,features:chosen,traffic,budget,timeline,experience});
  const toggle=(feature:string)=>setChosen(current=>current.includes(feature)?current.filter(item=>item!==feature):[...current,feature]);
  const next=async()=>{
    if(step!==1){setStep(current=>Math.min(3,current+1));return}
    setClarifying(true);
    try{const result=await analysisService.clarifications(context());setQuestions(result.questions??[]);setStep(2)}
    catch{toast.error("Could not prepare clarification questions. Please retry.")}
    finally{setClarifying(false)}
  };
  const submit=async()=>{
    setBusy(true);
    try{const result=await analysisService.startIdea({...context(),clarifications:answers});toast.success("Idea analysis started");router.push(`/projects/${result.projectId||result.id}/processing`)}
    catch{toast.error("Could not start the analysis.")}
    finally{setBusy(false)}
  };
  return <WizardShell title="New Development Idea" description="Describe what you want to build in normal language, then answer only the questions needed to improve the recommendation." steps={["Idea","Project Context","AI Clarification","Review"]} current={step}>
    <Card className="overflow-hidden"><div className="h-2 bg-gradient-to-r from-amber-500 via-rose-500 to-emerald-500"/><CardContent className="p-6 pt-6">
      {step===0&&<div><div className="mb-5 flex items-center gap-3"><div className="grid size-12 place-items-center rounded-2xl bg-amber-500/10 text-amber-500"><WandSparkles className="size-5"/></div><div><h2 className="text-xl font-black">Tell us what you want to build...</h2><p className="text-sm text-[var(--muted-foreground)]">You do not need to know the hosting or technology yet.</p></div></div><Textarea className="min-h-52 text-base leading-7" value={idea} onChange={event=>setIdea(event.target.value)} placeholder={example}/><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setIdea(example)}>Use Example</Button><Button variant="ghost" onClick={()=>setIdea("")}><X className="size-4"/>Clear</Button></div></div>}
      {step===1&&<IdeaContext industry={industry} setIndustry={setIndustry} users={users} setUsers={setUsers} traffic={traffic} setTraffic={setTraffic} budget={budget} setBudget={setBudget} timeline={timeline} setTimeline={setTimeline} experience={experience} setExperience={setExperience} chosen={chosen} toggle={toggle}/>}
      {step===2&&<div><div className="mb-5 flex items-center gap-3"><Sparkles className="size-6 text-emerald-500"/><div><h2 className="text-xl font-black">A few clarification questions</h2><p className="text-sm text-[var(--muted-foreground)]">Generated by the backend from information still missing for confident workload and cost sizing.</p></div></div>{questions.length?<div className="grid gap-4">{questions.map(question=><Field key={question.key} label={question.question} hint={question.required_for_confidence?"This answer improves recommendation confidence.":undefined}>{question.input_type==="SELECT"?<Select value={answers[question.key]??""} onChange={event=>setAnswers(current=>({...current,[question.key]:event.target.value}))}><option value="">Select an answer</option>{(question.options??[]).map(option=><option key={option}>{option}</option>)}</Select>:<Input type={question.input_type==="NUMBER"?"number":"text"} min={question.input_type==="NUMBER"?"0":undefined} value={answers[question.key]??""} onChange={event=>setAnswers(current=>({...current,[question.key]:event.target.value}))}/>}</Field>)}</div>:<div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5 text-sm">Your current inputs are complete enough for this analysis. You can continue without additional answers.</div>}</div>}
      {step===3&&<div><h2 className="text-xl font-black">Review idea context</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">Clarification answers are saved to the project database and used directly by workload, cost, resource sizing, and recommendation logic.</p><div className="mt-5 grid gap-3"><Summary k="Idea" v={idea}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Summary k="Industry" v={industry}/><Summary k="Target users" v={users}/><Summary k="Traffic" v={traffic}/><Summary k="Budget" v={`$${budget}/month`}/><Summary k="Timeline" v={timeline}/><Summary k="Experience" v={experience}/></div><Summary k="Features" v={chosen.join(", ")}/>{questions.map(question=><Summary key={question.key} k={question.question} v={answers[question.key]||"Not provided - confidence will reflect this"}/>)}</div></div>}
    </CardContent></Card>
    <div className="sticky bottom-16 mt-4 flex justify-between rounded-2xl border bg-[var(--background)]/90 p-3 backdrop-blur lg:bottom-2"><Button variant="ghost" disabled={step===0||clarifying} onClick={()=>setStep(current=>current-1)}><ArrowLeft className="size-4"/>Back</Button>{step<3?<Button variant="gradient" disabled={(step===0&&!idea.trim())||clarifying} onClick={next}>{clarifying?<><Loader2 className="size-4 animate-spin"/>Preparing...</>:<>Continue<ArrowRight className="size-4"/></>}</Button>:<Button variant="gradient" disabled={busy} onClick={submit}>{busy?<><Loader2 className="size-4 animate-spin"/>Starting...</>:"Generate Analysis"}</Button>}</div>
  </WizardShell>
}

function IdeaContext({industry,setIndustry,users,setUsers,traffic,setTraffic,budget,setBudget,timeline,setTimeline,experience,setExperience,chosen,toggle}:{industry:string;setIndustry:(v:string)=>void;users:string;setUsers:(v:string)=>void;traffic:string;setTraffic:(v:string)=>void;budget:string;setBudget:(v:string)=>void;timeline:string;setTimeline:(v:string)=>void;experience:string;setExperience:(v:string)=>void;chosen:string[];toggle:(v:string)=>void}){return <div className="grid gap-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Industry"><Select value={industry} onChange={event=>setIndustry(event.target.value)}>{["E-commerce","Education","Healthcare","Finance","Entertainment","Media","Travel","Food","SaaS","Social","Non-profit","Government","Other"].map(item=><option key={item}>{item}</option>)}</Select></Field><Field label="Target Users"><Input value={users} onChange={event=>setUsers(event.target.value)}/></Field><Field label="Expected Traffic"><Select value={traffic} onChange={event=>setTraffic(event.target.value)}>{["Small local audience","Growing business","National audience","International audience","Large public platform"].map(item=><option key={item}>{item}</option>)}</Select></Field><Field label="Monthly Budget (USD)"><Input type="number" min="0" value={budget} onChange={event=>setBudget(event.target.value)}/></Field><Field label="Timeline"><Select value={timeline} onChange={event=>setTimeline(event.target.value)}>{["< 1 month","1–3 months","3–6 months","6–12 months","Not sure"].map(item=><option key={item}>{item}</option>)}</Select></Field><Field label="Developer Experience"><Select value={experience} onChange={event=>setExperience(event.target.value)}>{["Beginner","Intermediate","Advanced"].map(item=><option key={item}>{item}</option>)}</Select></Field></div><Field label="Main Features"><div className="flex flex-wrap gap-2">{features.map(feature=><button type="button" key={feature} onClick={()=>toggle(feature)} className={`rounded-full border px-3 py-2 text-xs font-bold ${chosen.includes(feature)?"border-emerald-500 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300":"hover:bg-[var(--muted)]"}`}>{chosen.includes(feature)&&<CheckCircle2 className="mr-1 inline size-3.5"/>}{feature}</button>)}</div></Field></div>}
function Summary({k,v}:{k:string;v:string}){return <div className="rounded-xl border p-4"><div className="text-[10px] font-black uppercase tracking-wide text-[var(--muted-foreground)]">{k}</div><div className="mt-1 text-sm font-semibold leading-6">{v||"Not provided"}</div></div>}
