from enum import StrEnum

class UserRole(StrEnum): USER="USER"
class UserStatus(StrEnum): ACTIVE="ACTIVE"; DISABLED="DISABLED"; PENDING="PENDING"
class Theme(StrEnum): LIGHT="LIGHT"; DARK="DARK"; SYSTEM="SYSTEM"
class ExperienceLevel(StrEnum): BEGINNER="BEGINNER"; INTERMEDIATE="INTERMEDIATE"; ADVANCED="ADVANCED"
class ProjectMode(StrEnum): LIVE_URL="LIVE_URL"; PLANNED="PLANNED"; NEW_IDEA="NEW_IDEA"
class ProjectStatus(StrEnum): DRAFT="DRAFT"; QUEUED="QUEUED"; ANALYSING="ANALYSING"; COMPLETED="COMPLETED"; NEEDS_ATTENTION="NEEDS_ATTENTION"; FAILED="FAILED"; CANCELLED="CANCELLED"; ARCHIVED="ARCHIVED"
class JobStatus(StrEnum): QUEUED="QUEUED"; RUNNING="RUNNING"; COMPLETED="COMPLETED"; FAILED="FAILED"; CANCELLED="CANCELLED"
class AnalysisStage(StrEnum):
    URL_VALIDATION="URL_VALIDATION"; TECHNOLOGY_DETECTION="TECHNOLOGY_DETECTION"; PERFORMANCE_AUDIT="PERFORMANCE_AUDIT"; WORKLOAD_CALCULATION="WORKLOAD_CALCULATION"; RULE_EVALUATION="RULE_EVALUATION"; ML_PREDICTION="ML_PREDICTION"; PRICING_COMPARISON="PRICING_COMPARISON"; FINAL_SCORING="FINAL_SCORING"; CONFIDENCE_CALCULATION="CONFIDENCE_CALCULATION"; OPTIMIZATION_GENERATION="OPTIMIZATION_GENERATION"; REPORT_PREPARATION="REPORT_PREPARATION"
class HostingType(StrEnum): VPS="VPS"; CLOUD_VM="CLOUD_VM"; KUBERNETES="KUBERNETES"
class ConfidenceLabel(StrEnum): HIGH="HIGH"; MEDIUM="MEDIUM"; LOW="LOW"; INSUFFICIENT_DATA="INSUFFICIENT_DATA"
class OptimizationPriority(StrEnum): CRITICAL="CRITICAL"; HIGH="HIGH"; MEDIUM="MEDIUM"; LOW="LOW"
class OptimizationStatus(StrEnum): OPEN="OPEN"; DONE="DONE"; NOT_RELEVANT="NOT_RELEVANT"
class TestType(StrEnum): UT="UT"; IT="IT"; ST="ST"; UAT="UAT"; ORT="ORT"
class LoadTestType(StrEnum): SMOKE="SMOKE"; LOAD="LOAD"; STRESS="STRESS"; SPIKE="SPIKE"; SOAK="SOAK"
