"use client";

import Link from "next/link";
import { use } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, ArrowRight, Bell, BrainCircuit, CheckCircle2, CircleDollarSign, FileText, Gauge, History, Loader2, Server, Sparkles, TestTube2 } from "lucide-react";
import { AnalysisCoverageChart, DecisionFactorsChart } from "@/components/charts/dashboard-charts";
import { ProjectHeader } from "@/components/projects/project-header";
import { ProjectTabs } from "@/components/projects/project-tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScoreRing } from "@/components/shared/score-ring";
import { Button } from "@/components/ui/button";
import { projectService } from "@/services/project-service";
import { projectDataService } from "@/services/project-data-service";

type Coverage={section:string;complete:boolean;count:number;note:string};
type Factor={factor:string;score:number;value:string;effect:string};
type TestCoverage={passed:number;failed:number;notRun:number;total:number};
type ProjectTest={code:string;status:string;actual:string;meaning:string};

export default function ProjectPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params);
  const project=useQuery({queryKey:["project",id],queryFn:()=>projectService.get(id)});
  const recommendation=useQuery({queryKey:["recommendation",id],queryFn:()=>projectDataService.recommendation(id),retry:false});
  const optimizations=useQuery({queryKey:["optimizations",id],queryFn:()=>projectDataService.optimizations(id),retry:false});
  const summary=useQuery({queryKey:["analysis-summary",id],queryFn:()=>projectDataService.analysisSummary(id),retry:false});
  return <div className="grid gap-6"><ProjectHeader id={id}/><ProjectTabs id={id} active=""/>{project.isLoading?<div className="grid min-h-52 place-items-center"><Loader2 className="size-6 animate-spin"/></div>:project.isError?<div className="rounded-2xl border p-8">Could not load project.</div>:<>
    <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card className="overflow-hidden border-emerald-500/20"><div className="h-2 bg-gradient-to-r from-emerald-500 via-emerald-500 to-amber-500"/><CardContent className="grid gap-6 p-6 pt-6 md:grid-cols-[auto_1fr] md:items-center"><ScoreRing value={recommendation.data?Math.round(recommendation.data.fitScore??0):0} label="Overall Recommendation Fit"/><div><div className="text-xs font-black uppercase tracking-[.18em] text-emerald-500">Recommended Hosting</div><h2 className="mt-2 text-3xl font-black">{recommendation.data?.recommended??"Pending"}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">Calculated from the exact saved inputs, workload, performance evidence, provider pricing, rules, and trained model output.</p><div className="mt-4 flex flex-wrap gap-2"><Button asChild variant="gradient"><Link href={`/projects/${id}/recommendation`}>View Why<ArrowRight className="size-4"/></Link></Button><Button asChild variant="outline"><Link href={`/projects/${id}/architecture`}>View Architecture</Link></Button><Button asChild variant="outline"><Link href={`/projects/${id}/cost`}>Estimate Cost</Link></Button></div></div></CardContent></Card><Card><CardHeader><CardTitle>Project Snapshot</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Snapshot icon={Gauge} k="Performance" v={project.data?.performanceScore?`${project.data.performanceScore}/100`:"—"}/><Snapshot icon={BrainCircuit} k="AI Confidence" v={project.data?.confidence?`${project.data.confidence}%`:"—"}/><Snapshot icon={CircleDollarSign} k="Monthly Range" v={project.data?.costRange?`$${project.data.costRange[0]}–$${project.data.costRange[1]}`:"—"}/><Snapshot icon={Server} k="Mode" v={project.data?.mode??"—"}/></CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Analysis coverage</CardTitle><CardDescription>Every project section and whether database evidence is available.</CardDescription></CardHeader><CardContent>{summary.isLoading?<Loading/>:<AnalysisCoverageChart data={summary.data?.coverage??[]}/>}</CardContent></Card><Card><CardHeader><CardTitle>Why the decision changed</CardTitle><CardDescription>Normalized influence indicators derived from this project’s input and evidence.</CardDescription></CardHeader><CardContent>{summary.isLoading?<Loading/>:<DecisionFactorsChart data={summary.data?.decisionFactors??[]}/>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Input knowledge summary</CardTitle><CardDescription>Values actually stored and used by the pipeline. Unknown values remain explicit.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(summary.data?.input??{}).map(([key,value])=><div key={key} className="rounded-xl border p-4"><div className="text-[10px] font-black uppercase tracking-wide text-[var(--muted-foreground)]">{label(key)}</div><div className="mt-2 break-words text-sm font-semibold">{display(value)}</div></div>)}</CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><div className="flex items-center gap-2"><Sparkles className="size-5 text-emerald-500"/><CardTitle>Your Next Actions</CardTitle></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{optimizations.data?.length?optimizations.data.slice(0,8).map((item:{id:string;title:string},index:number)=><Link key={item.id} href={`/projects/${id}/optimization`} className="flex gap-3 rounded-xl border p-4 hover:bg-[var(--muted)]"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-emerald-500/10 text-xs font-black text-emerald-500">{index+1}</span><span className="text-sm font-semibold">{item.title}</span></Link>):<div className="text-sm text-[var(--muted-foreground)]">No optimization actions are available yet.</div>}</CardContent></Card><ActivitySummary data={summary.data?.activity}/></div>
    <div className="grid gap-4 lg:grid-cols-5">{Object.entries((summary.data?.testing??{}) as Record<string,TestCoverage>).map(([type,result])=><Card key={type}><CardContent className="p-5 pt-5"><div className="flex items-center justify-between"><TestTube2 className="size-5 text-emerald-500"/><strong>{type}</strong></div><div className="mt-4 text-3xl font-black">{result.passed}/{result.total}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">passed · {result.failed} failed · {result.notRun} not run</div></CardContent></Card>)}</div>
    {summary.data?.projectTests?.length?<Card><CardHeader><CardTitle>Tests for this exact input</CardTitle><CardDescription>System validation generated from this project’s mode, stored inputs, analysis evidence, recommendation, cost, optimizations, report, and load-test safeguards.</CardDescription></CardHeader><CardContent className="grid gap-3">{(summary.data.projectTests as ProjectTest[]).map(test=><div key={test.code} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_auto] md:items-start"><div><div className="flex flex-wrap items-center gap-2"><strong>{label(test.code)}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-black ${test.status==="PASSED"?"bg-emerald-500/10 text-emerald-600":test.status==="WARNING"?"bg-amber-500/10 text-amber-600":"bg-red-500/10 text-red-600"}`}>{test.status}</span></div><p className="mt-2 text-sm text-[var(--muted-foreground)]">{test.meaning}</p></div><div className="rounded-lg bg-[var(--muted)] px-3 py-2 text-xs font-semibold md:max-w-72">Observed: {test.actual}</div></div>)}</CardContent></Card>:null}
    {summary.data?.decisionFactors?.length?<Card><CardHeader><CardTitle>Detailed decision knowledge</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{(summary.data.decisionFactors as Factor[]).map(item=><div key={item.factor} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{item.factor}</strong><span>{item.score}/100</span></div><div className="mt-2 text-sm font-semibold text-emerald-600 dark:text-emerald-300">{item.value}</div><p className="mt-2 text-sm text-[var(--muted-foreground)]">{item.effect}</p></div>)}</CardContent></Card>:null}
    {recommendation.data?.assumptions?.length?<Card><CardHeader><CardTitle>Assumptions Used</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{recommendation.data.assumptions.map((item:string)=><span key={item} className="rounded-full bg-[var(--muted)] px-3 py-2 text-xs font-semibold">{item}</span>)}</CardContent></Card>:null}
  </>}</div>
}

function ActivitySummary({data}:{data?:{events:number;notifications:number;reports:number;feedback:number;loadTestPlans:number;loadTestResults:number}}){const rows=[["History events",data?.events??0,History],["Notifications",data?.notifications??0,Bell],["Reports",data?.reports??0,FileText],["Load-test plans",data?.loadTestPlans??0,Activity],["Load-test results",data?.loadTestResults??0,CheckCircle2],["UAT feedback",data?.feedback??0,TestTube2]] as const;return <Card><CardHeader><CardTitle>Connected records</CardTitle><CardDescription>Related database evidence across the complete workflow.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3">{rows.map(([name,value,Icon])=><div key={name} className="rounded-xl bg-[var(--muted)] p-4"><Icon className="size-4 text-emerald-500"/><div className="mt-2 text-2xl font-black">{value}</div><div className="text-xs text-[var(--muted-foreground)]">{name}</div></div>)}</CardContent></Card>}
function Snapshot({icon:Icon,k,v}:{icon:typeof Gauge;k:string;v:string}){return <div className="rounded-xl bg-[var(--muted)] p-4"><Icon className="size-5 text-emerald-500"/><div className="mt-3 text-[10px] font-black uppercase tracking-wide text-[var(--muted-foreground)]">{k}</div><div className="mt-1 text-sm font-black">{v}</div></div>}
function Loading(){return <div className="grid h-72 place-items-center"><Loader2 className="size-6 animate-spin text-emerald-500"/></div>}
function label(value:string){return value.replaceAll(/([A-Z])/g," $1").replaceAll("_"," ")}
function display(value:unknown){if(value===null||value===undefined||value==="")return "Not provided";if(typeof value==="boolean")return value?"Yes":"No";if(Array.isArray(value))return value.join(", ")||"None";if(typeof value==="object")return Object.entries(value as Record<string,unknown>).map(([key,item])=>`${label(key)}: ${String(item)}`).join(" · ");return String(value)}
