"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { ArrowRight, CircleDollarSign, Database, Gauge, Loader2, Server, TriangleAlert } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/input";
import { pricingService } from "@/services/pricing-service";
import { projectService } from "@/services/project-service";

type Plan={id:string;provider:string;plan:string;architecture:string;vcpu:number;ramGb:number;storageGb:number;monthlyRange:[number,number];updatedAt:string;isStale:boolean};
type Component={name:string;min:number;max:number;share:number;status:string};
type CostData={currency:string;architecture:string;resources:Record<string,unknown>;recommended_range:{min:number|null;max:number|null};budget:number|null;budget_tier:string;budget_status:string;budget_utilization_percent:number|null;budget_headroom:number|null;budget_explanation:string;cost_optimization?:{method:string;estimated_monthly_savings:number|null;estimated_annual_savings:number|null;savings_status:string;guardrail:string;actions:Array<{priority:number;title:string;detail:string}>};decision_evidence?:{classifier?:{output:string;source:string;version:string};resource_sizer?:{source:string;version:string}};llm_explanation?:{content?:{summary?:string;cost_explanation?:string}};llm_status?:string;llm_model?:string|null;components:Component[];providers:Plan[];pricing_updated_at:string|null;warnings:string[]};
const money=(v:number|null|undefined)=>v==null?"Unavailable":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const statusTone=(s:string)=>s==="WITHIN_BUDGET"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300":s==="PARTIALLY_WITHIN_BUDGET"?"border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-300":"border-rose-500/30 bg-rose-500/10 text-rose-700 dark:text-rose-300";

export default function CostExplorer(){
  const projects=useQuery({queryKey:["projects"],queryFn:projectService.list});
  const completed=useMemo(()=>(projects.data??[]).filter(p=>p.status==="Completed"),[projects.data]);
  const [projectId,setProjectId]=useState("");const [architecture,setArchitecture]=useState("");
  useEffect(()=>{if(!projectId&&completed[0])setProjectId(completed[0].id)},[completed,projectId]);
  const cost=useQuery<CostData>({queryKey:["project-cost",projectId],queryFn:()=>pricingService.projectCost(projectId),enabled:Boolean(projectId)});
  const plans=useQuery<{currency:string;plans:Plan[]}>({queryKey:["pricing-compare",architecture],queryFn:()=>pricingService.compare(architecture)});
  const selected=completed.find(p=>p.id===projectId);const data=cost.data;const range=data?.recommended_range;
  const barMax=Math.max(data?.budget||0,range?.max||0,1);const budgetWidth=Math.min(100,((data?.budget||0)/barMax)*100);const costWidth=Math.min(100,((range?.max||0)/barMax)*100);
  if(projects.isLoading)return <div className="grid min-h-72 place-items-center"><Loader2 className="size-7 animate-spin text-emerald-500"/></div>;
  return <div className="grid gap-6"><PageHeader eyebrow="AI Advisor" title="Cost Explorer" description="Compare database-backed USD estimates against each project’s budget, resource size and architecture."/>
    {completed.length?<><Card><CardContent className="grid gap-4 p-5 pt-5 md:grid-cols-[1fr_auto] md:items-end"><label className="grid gap-2 text-sm font-bold">Analysed project<Select value={projectId} onChange={e=>setProjectId(e.target.value)}>{completed.map(p=><option key={p.id} value={p.id}>{p.name} · {p.mode}</option>)}</Select></label>{selected&&<Button asChild variant="outline"><Link href={`/projects/${selected.id}/cost`}>Open project details<ArrowRight className="size-4"/></Link></Button>}</CardContent></Card>
    {cost.isLoading?<div className="grid min-h-64 place-items-center"><Loader2 className="size-7 animate-spin text-emerald-500"/></div>:cost.isError||!data?<Card><CardContent className="p-8 text-center">The selected project does not have a complete cost recommendation.</CardContent></Card>:<>
      <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Recommended range" value={`${money(range?.min)} – ${money(range?.max)}`}/><Metric icon={Gauge} label="Your monthly budget" value={money(data.budget)}/><Metric icon={Server} label="Architecture" value={data.architecture.replaceAll("_"," ")}/><Metric icon={Database} label="Starting resources" value={`${data.resources.vcpu??"?"} vCPU · ${data.resources.ram_gb??"?"} GB RAM`}/></motion.div>
      <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>Budget compatibility</CardTitle><CardDescription>{data.budget_explanation}</CardDescription></div><Badge className={statusTone(data.budget_status)}>{data.budget_status.replaceAll("_"," ")}</Badge></div></CardHeader><CardContent className="grid gap-5"><div className="relative h-5 overflow-hidden rounded-full bg-[var(--muted)]"><motion.div initial={{width:0}} animate={{width:`${costWidth}%`}} transition={{duration:.8}} className="absolute inset-y-0 left-0 rounded-full bg-gradient-to-r from-emerald-600 to-amber-400"/><div className="absolute inset-y-0 border-r-2 border-dashed border-foreground" style={{left:`${budgetWidth}%`}}/></div><div className="flex flex-wrap justify-between gap-2 text-sm"><span>Estimated maximum: <strong>{money(range?.max)}</strong></span><span>Budget: <strong>{money(data.budget)}</strong></span><span>Headroom: <strong>{data.budget_headroom==null?"Unavailable":money(data.budget_headroom)}</strong></span></div></CardContent></Card>
      <div className="grid gap-5 lg:grid-cols-2"><Card className="border-fuchsia-500/20"><CardHeader><CardTitle>Two models + OpenRouter GLM 5.2</CardTitle><CardDescription>{String(data.llm_status??"NOT CONFIGURED").replaceAll("_"," ")} · {data.llm_model??"Deterministic fallback"}</CardDescription></CardHeader><CardContent className="grid gap-3"><Line label="Classifier" value={`${String(data.decision_evidence?.classifier?.output??"Unavailable").replaceAll("_"," ")} · ${data.decision_evidence?.classifier?.source??"UNKNOWN"}`}/><Line label="Resource model" value={`${data.decision_evidence?.resource_sizer?.source??"UNKNOWN"} · ${data.decision_evidence?.resource_sizer?.version??"Unavailable"}`}/><p className="text-sm leading-6">{data.llm_explanation?.content?.summary??"Rules, trained models, and stored pricing produced the decision."}</p></CardContent></Card><Card className="border-cyan-500/20"><CardHeader><CardTitle>Cost optimization</CardTitle><CardDescription>{data.cost_optimization?.guardrail??"Savings require a supplied current monthly cost."}</CardDescription></CardHeader><CardContent className="grid gap-3"><Line label="Monthly savings" value={data.cost_optimization?.estimated_monthly_savings==null?"Needs current cost":money(data.cost_optimization.estimated_monthly_savings)}/><Line label="Annual savings" value={data.cost_optimization?.estimated_annual_savings==null?"Needs current cost":money(data.cost_optimization.estimated_annual_savings)}/>{(data.cost_optimization?.actions??[]).slice(0,3).map(action=><div key={action.priority} className="rounded-xl border p-3"><strong>{action.priority}. {action.title}</strong><p className="mt-1 text-xs leading-5 text-[var(--muted-foreground)]">{action.detail}</p></div>)}</CardContent></Card></div>
      <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><Card><CardHeader><CardTitle>Estimated monthly components</CardTitle><CardDescription>Transparent allocation of the range; provider bills can vary.</CardDescription></CardHeader><CardContent className="grid gap-4">{data.components.map((item,index)=><div key={item.name}><div className="mb-1 flex justify-between gap-3 text-sm"><strong>{item.name}</strong><span>{money(item.min)} – {money(item.max)} · {item.share}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[var(--muted)]"><motion.div initial={{width:0}} animate={{width:`${item.share}%`}} transition={{duration:.6,delay:index*.08}} className="h-full rounded-full bg-emerald-500"/></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Decision context</CardTitle><CardDescription>What the estimate means for this project.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm"><Line label="Budget tier" value={data.budget_tier.replaceAll("_"," ")}/><Line label="Budget used at maximum" value={data.budget_utilization_percent==null?"Unavailable":`${data.budget_utilization_percent}%`}/><Line label="Pricing captured" value={data.pricing_updated_at?new Date(data.pricing_updated_at).toLocaleDateString():"Unavailable"}/>{data.warnings.map(w=><div key={w} className="flex gap-2 rounded-xl border border-amber-500/30 bg-amber-500/5 p-3"><TriangleAlert className="mt-0.5 size-4 shrink-0 text-amber-500"/><span>{w}</span></div>)}</CardContent></Card></div>
      <PlanTable title="Matching provider plans" description="Plans large enough for the recommended starting resources." plans={data.providers}/>
    </>}
    <Card><CardHeader><CardTitle>Explore all stored pricing</CardTitle><CardDescription>Filter the pricing cache to compare VPS, Cloud VM and Kubernetes options.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3"><label className="grid gap-2 text-sm font-bold">Architecture<Select value={architecture} onChange={e=>setArchitecture(e.target.value)}><option value="">All architectures</option><option value="VPS">VPS</option><option value="CLOUD_VM">Cloud VM</option><option value="KUBERNETES">Kubernetes</option></Select></label></div>{plans.isLoading?<Loader2 className="mx-auto size-6 animate-spin"/>:<PlanTable title="" description="" plans={plans.data?.plans??[]}/>}</CardContent></Card></>:<Card><CardContent className="p-8 text-center"><p className="font-bold">Complete an analysis in any input mode to calculate a project-specific cost.</p><Button asChild className="mt-4"><Link href="/projects/new">New Analysis</Link></Button></CardContent></Card>}
  </div>
}

function Metric({icon:Icon,label,value}:{icon:typeof Server;label:string;value:string}){return <Card><CardContent className="p-5 pt-5"><Icon className="size-5 text-emerald-500"/><div className="mt-4 text-xs font-bold uppercase tracking-wide text-[var(--muted-foreground)]">{label}</div><div className="mt-1 text-xl font-black">{value}</div></CardContent></Card>}
function Line({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 rounded-xl bg-[var(--muted)] p-3"><span className="text-[var(--muted-foreground)]">{label}</span><strong className="text-right">{value}</strong></div>}
function PlanTable({title,description,plans}:{title:string;description:string;plans:Plan[]}){return <Card className={!title?"border-0 shadow-none":""}>{title&&<CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader>}<CardContent className={!title?"p-0":""}>{plans.length?<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wide text-[var(--muted-foreground)]"><th className="p-3">Provider / plan</th><th className="p-3">Architecture</th><th className="p-3">Resources</th><th className="p-3">Monthly range</th><th className="p-3">Freshness</th></tr></thead><tbody>{plans.map(p=><tr key={p.id} className="border-b last:border-0"><td className="p-3"><strong>{p.provider}</strong><div className="text-[var(--muted-foreground)]">{p.plan}</div></td><td className="p-3">{p.architecture.replaceAll("_"," ")}</td><td className="p-3">{p.vcpu} vCPU · {p.ramGb} GB · {p.storageGb} GB</td><td className="p-3 font-bold">{money(p.monthlyRange[0])} – {money(p.monthlyRange[1])}</td><td className="p-3"><Badge className={p.isStale?"border-amber-500/30 text-amber-600":"border-emerald-500/30 text-emerald-600"}>{p.isStale?"Needs review":"Current cache"}</Badge></td></tr>)}</tbody></table></div>:<p className="py-6 text-center text-sm text-[var(--muted-foreground)]">No stored plans match these filters.</p>}</CardContent></Card>}
