"use client";

import { useQuery } from "@tanstack/react-query";
import { Cloud, DollarCircle, StatusUp } from "reicon-react";
import { Loader2 } from "lucide-react";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { CostBreakdownChart } from "@/components/charts/dashboard-charts";
import { projectDataService } from "@/services/project-data-service";

type Ranked={rank:number;architecture:string;display_name:string;fit_score:number;monthly_range:{min:number|null;max:number|null};annual_range:{min:number|null;max:number|null};budget_status:string;pricing_evidence:string;score_breakdown?:{raw?:Record<string,number>;rule_delta?:number;final_score?:number}};
type Provider={id:string;provider:string;plan:string;monthlyRange:[number,number];vcpu:number;ramGb:number;storageGb:number;source?:string;isDemo?:boolean;isEstimate?:boolean;pricingMethod?:string;scaleFactor?:number;isStale?:boolean;freshnessWarning?:string};
const tones:Record<string,string>={WITHIN_BUDGET:"bg-emerald-500/10 text-emerald-600 dark:text-emerald-300",PARTIALLY_WITHIN_BUDGET:"bg-amber-500/10 text-amber-600 dark:text-amber-300",OVER_BUDGET:"bg-rose-500/10 text-rose-600 dark:text-rose-300",PRICING_UNAVAILABLE:"bg-slate-500/10 text-slate-600 dark:text-slate-300",BUDGET_NOT_PROVIDED:"bg-indigo-500/10 text-indigo-600 dark:text-indigo-300"};

export function AdvancedCost({id}:{id:string}){
  const query=useQuery({queryKey:["project-cost",id],queryFn:()=>projectDataService.cost(id)});
  if(query.isLoading)return <div className="grid min-h-52 place-items-center"><Loader2 className="size-6 animate-spin text-indigo-500"/></div>;
  if(query.isError)return <Card><CardContent className="p-8">Cost analysis could not be loaded.</CardContent></Card>;
  const data=query.data;const range=data.recommended_range??{};const annual=data.annual_range??{};const ranked=(data.ranked_options??[]) as Ranked[];const providers=(data.providers??[]) as Provider[];const optimization=data.cost_optimization??{};const evidence=data.decision_evidence??{};const ai=data.llm_explanation?.content??{};
  return <div className="grid gap-5">
    <div><div className="text-xs font-black uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-300">Rules · weighted scoring · stored USD ranges</div><h1 className="mt-2 text-3xl font-black tracking-tight">Cost and hosting ranking</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted-foreground)]">VPS, Cloud VM, and Kubernetes are ranked using traffic, budget, scalability, reliability, operational fit, model probability, and explicit rule adjustments.</p></div>
    <Card className="overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-indigo-500 via-cyan-500 to-violet-500"/><CardContent className="grid gap-5 p-6 pt-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="text-xs font-black uppercase tracking-wide text-[var(--muted-foreground)]">Recommended architecture</div><h2 className="mt-2 text-4xl font-black">{String(data.architecture).replaceAll("_"," ")}</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">{data.budget_explanation}</p></div><Status value={data.budget_status}/></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={DollarCircle} label="Monthly range" value={money(range.min,range.max)}/><Kpi icon={DollarCircle} label="Annual range" value={money(annual.min,annual.max)}/><Kpi icon={StatusUp} label="Budget utilization" value={data.budget_utilization_percent==null?"Unavailable":`${data.budget_utilization_percent}%`}/><Kpi icon={Cloud} label="Matching providers" value={String(data.matching_provider_count??0)}/></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card className="overflow-hidden"><div className="h-1 bg-gradient-to-r from-fuchsia-500 to-indigo-500"/><CardHeader><CardTitle>Two-model decision evidence</CardTitle><CardDescription>OpenRouter explains the result; it cannot alter these model outputs or stored costs.</CardDescription></CardHeader><CardContent className="grid gap-3"><Evidence label="Hosting classifier" value={`${String(evidence.classifier?.output??"Unavailable").replaceAll("_"," ")} · ${evidence.classifier?.source??"UNKNOWN"}`} detail={evidence.classifier?.version}/><Evidence label="Resource sizing model" value={`${data.resources?.vcpu??"—"} vCPU · ${data.resources?.ram_gb??"—"} GB RAM`} detail={`${evidence.resource_sizer?.version??"Unavailable"} · ${evidence.resource_sizer?.source??"UNKNOWN"}`}/><Evidence label="OpenRouter · GLM 5.2" value={String(data.llm_status??"NOT CONFIGURED").replaceAll("_"," ")} detail={data.llm_model??"Deterministic fallback"}/></CardContent></Card><Card className="overflow-hidden"><div className="h-1 bg-gradient-to-r from-cyan-500 to-emerald-500"/><CardHeader><CardTitle>AI advisor explanation</CardTitle><CardDescription>GLM 5.2 explanation grounded in persisted ranking evidence.</CardDescription></CardHeader><CardContent><p className="text-sm leading-6">{ai.summary??"The deterministic ranking and cost evidence are shown below."}</p><p className="mt-3 text-sm leading-6 text-[var(--muted-foreground)]">{ai.cost_explanation??data.budget_explanation}</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Cost optimization plan</CardTitle><CardDescription>{optimization.guardrail??"Optimization uses model right-sizing and stored provider prices."}</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{(optimization.actions??[]).map((action:{priority:number;title:string;detail:string})=><div key={action.priority} className="rounded-2xl border bg-gradient-to-br from-white/5 to-indigo-500/5 p-4"><span className="grid size-8 place-items-center rounded-lg bg-indigo-500/10 text-xs font-black text-indigo-600">{action.priority}</span><div className="mt-3 font-black">{action.title}</div><p className="mt-2 text-xs leading-5 text-[var(--muted-foreground)]">{action.detail}</p></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Evidence label="Budget tier" value={String(optimization.budget_tier??"Unavailable").replaceAll("_"," ")}/><Evidence label="Monthly savings" value={optimization.estimated_monthly_savings==null?"Needs current cost":`$${optimization.estimated_monthly_savings}`}/><Evidence label="Annual savings" value={optimization.estimated_annual_savings==null?"Needs current cost":`$${optimization.estimated_annual_savings}`}/></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Ranked hosting options</CardTitle><CardDescription>The ranking below is the same persisted decision evidence used by the recommendation engine.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-3">{ranked.map(option=><div key={option.architecture} className={`rounded-2xl border p-5 ${option.rank===1?"border-indigo-500/40 bg-gradient-to-br from-indigo-500/10 to-cyan-500/5":""}`}><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-indigo-500/10 text-sm font-black text-indigo-600">#{option.rank}</span><Status value={option.budget_status}/></div><h3 className="mt-4 text-xl font-black">{option.display_name}</h3><div className="mt-1 text-sm text-[var(--muted-foreground)]">Fit score {option.fit_score}/100</div><div className="mt-4 rounded-xl bg-[var(--muted)] p-3"><div className="text-xs text-[var(--muted-foreground)]">Monthly</div><div className="font-black">{money(option.monthly_range.min,option.monthly_range.max)}</div><div className="mt-2 text-xs text-[var(--muted-foreground)]">Annual</div><div className="font-bold">{money(option.annual_range.min,option.annual_range.max)}</div></div><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(option.score_breakdown?.raw??{}).map(([name,value])=><div key={name} className="rounded-lg border px-2 py-2"><div className="text-[9px] font-black uppercase text-[var(--muted-foreground)]">{name}</div><div className="text-sm font-black">{value}/100</div></div>)}</div><div className="mt-3 text-[10px] font-bold uppercase tracking-wide text-[var(--muted-foreground)]">{option.pricing_evidence.replaceAll("_"," ")}</div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Monthly cost composition</CardTitle><CardDescription>Architecture allocation estimates explain the range; provider plans remain the authoritative stored price evidence.</CardDescription></CardHeader><CardContent><CostBreakdownChart data={data.components??[]}/></CardContent></Card>
    <Card><CardHeader><CardTitle>Provider pricing evidence</CardTitle><CardDescription>Exact matching plans are preferred. Resource-scaled estimates are clearly labelled and remain traceable to a stored base plan.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{providers.length?providers.map(provider=><div key={provider.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div className="font-black">{provider.provider} · {provider.plan}</div><div className="flex gap-1">{provider.isEstimate?<span className="rounded-full bg-fuchsia-500/10 px-2 py-1 text-[10px] font-black text-fuchsia-600">MODEL-SCALED</span>:null}{provider.isDemo?<span className="rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-black text-amber-600">DEMO</span>:null}</div></div><div className="mt-2 text-sm text-[var(--muted-foreground)]">{provider.vcpu} vCPU · {provider.ramGb} GB RAM · {provider.storageGb} GB</div><div className="mt-3 text-lg font-black">{money(provider.monthlyRange[0],provider.monthlyRange[1])}</div><div className="mt-2 text-[10px] text-[var(--muted-foreground)]">{provider.source||"Stored pricing source"}{provider.scaleFactor?` · ${provider.scaleFactor}× resource factor`:""}{provider.isStale?" · STALE":""}</div>{provider.freshnessWarning?<p className="mt-2 text-xs text-amber-600">{provider.freshnessWarning}</p>:null}</div>):<Empty text="No stored provider evidence is available, so no cost was invented."/>}</CardContent></Card>
    {data.warnings?.length?<Card><CardHeader><CardTitle>Pricing limitations</CardTitle></CardHeader><CardContent className="grid gap-2">{data.warnings.map((warning:string)=><div key={warning} className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-sm">{warning}</div>)}</CardContent></Card>:null}
  </div>;
}

function money(min:number|null|undefined,max:number|null|undefined){return min==null||max==null?"Unavailable":`$${min.toLocaleString()} – $${max.toLocaleString()}`}
function Status({value}:{value:string}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${tones[value]||tones.PRICING_UNAVAILABLE}`}>{String(value||"UNKNOWN").replaceAll("_"," ")}</span>}
function Kpi({icon:Icon,label,value}:{icon:typeof Cloud;label:string;value:string}){return <Card className="card-hover"><CardContent className="p-5 pt-5"><span className="grid size-10 place-items-center rounded-xl bg-indigo-500/10 text-indigo-600"><Icon className="size-5" color="currentColor"/></span><div className="mt-4 text-xs font-bold text-[var(--muted-foreground)]">{label}</div><div className="mt-1 text-xl font-black">{value}</div></CardContent></Card>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-6 text-center text-sm text-[var(--muted-foreground)]">{text}</div>}
function Evidence({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="rounded-xl border p-3"><div className="text-[10px] font-black uppercase tracking-wide text-[var(--muted-foreground)]">{label}</div><div className="mt-1 font-black">{value}</div>{detail?<div className="mt-1 break-all text-[10px] text-[var(--muted-foreground)]">{detail}</div>:null}</div>}
