"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, Chart, Cpu, StatusUp } from "reicon-react";
import { Loader2 } from "lucide-react";
import {PolarAngleAxis,PolarGrid,Radar,RadarChart,ResponsiveContainer,Tooltip} from "recharts";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { PerformanceChart,WebVitalsChart } from "@/components/charts/dashboard-charts";
import { projectDataService } from "@/services/project-data-service";

type MetricStatus="GOOD"|"NEEDS_IMPROVEMENT"|"POOR"|"UNKNOWN";
type FieldMetric={value:number|null;category:MetricStatus;percentile:number};
type Audit={status:string;source?:string;warning?:string;performance_score:number|null;accessibility_score:number|null;best_practices_score:number|null;seo_score:number|null;metrics:Record<string,unknown>;core_web_vitals?:{overall_status?:string;statuses?:Record<string,MetricStatus>};lab_metrics?:Record<string,number|null>;field_data?:{page?:{id?:string;metrics?:Record<string,FieldMetric>};origin?:{id?:string;metrics?:Record<string,FieldMetric>}};opportunities?:Array<{id:string;title:string;display_value?:string;savings_ms:number;savings_bytes:number}>;metric_sources?:Record<string,string>};

const statusTone:Record<string,string>={GOOD:"bg-emerald-500/10 text-emerald-600 dark:text-emerald-300",PASSED:"bg-emerald-500/10 text-emerald-600 dark:text-emerald-300",NEEDS_IMPROVEMENT:"bg-amber-500/10 text-amber-600 dark:text-amber-300",POOR:"bg-rose-500/10 text-rose-600 dark:text-rose-300",FAILED:"bg-rose-500/10 text-rose-600 dark:text-rose-300",UNKNOWN:"bg-slate-500/10 text-slate-600 dark:text-slate-300",INSUFFICIENT_DATA:"bg-slate-500/10 text-slate-600 dark:text-slate-300",PLANNED:"bg-indigo-500/10 text-indigo-600 dark:text-indigo-300"};

export function AdvancedPerformance({id}:{id:string}){
  const [device,setDevice]=useState<"mobile"|"desktop">("mobile");
  const query=useQuery({queryKey:["performance",id],queryFn:()=>projectDataService.performance(id)});
  const history=useQuery({queryKey:["performance-history",id],queryFn:()=>projectDataService.performanceHistory(id)});
  if(query.isLoading)return <Loading/>;
  if(query.isError)return <Card><CardContent className="p-8 text-sm">Performance evidence could not be loaded.</CardContent></Card>;
  const audit=query.data?.[device] as Audit|undefined;const planned=audit?.status==="PLANNED";
  return <div className="grid gap-5">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-black uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-300">PageSpeed · Lighthouse · Core Web Vitals</div><h1 className="mt-2 text-3xl font-black tracking-tight">Performance analysis</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted-foreground)]">{planned?"Pre-launch budgets are shown as targets and never presented as measurements.":"CrUX field experience and Lighthouse lab evidence are kept separate, with field LCP, INP, and CLS preferred when available."}</p></div><div className="flex rounded-xl bg-[var(--muted)] p-1">{(["mobile","desktop"] as const).map(name=><button key={name} className={`rounded-lg px-4 py-2 text-xs font-bold capitalize ${device===name?"bg-[var(--card)] text-indigo-600 shadow-sm":"text-[var(--muted-foreground)]"}`} onClick={()=>setDevice(name)}>{name}</button>)}</div></div>
    {!audit?<Empty text={`No ${device} performance audit is available.`}/>:<>
      <Card className="overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-indigo-500 via-cyan-500 to-violet-500"/><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5 pt-5"><div><div className="text-sm font-black">Evidence source</div><div className="mt-1 text-sm text-[var(--muted-foreground)]">{audit.source||"Unknown source"}</div></div><Status value={planned?"PLANNED":audit.core_web_vitals?.overall_status||"INSUFFICIENT_DATA"}/></CardContent></Card>
      {audit.warning?<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm">{audit.warning}</div>:null}
      {planned?<Planned metrics={audit.metrics}/>:<Live audit={audit}/>} 
    </>}
    <Card><CardHeader><CardTitle>Performance history</CardTitle><CardDescription>Measured Lighthouse performance scores for the selected device.</CardDescription></CardHeader><CardContent><PerformanceChart data={(history.data??[]).filter((row:{strategy:string;performance:number|null})=>row.strategy.toLowerCase()===device&&row.performance!=null).map((row:{date:string;performance:number|null})=>({date:row.date,performance:row.performance}))}/></CardContent></Card>
  </div>;
}

function Live({audit}:{audit:Audit}){const cwv=audit.core_web_vitals?.statuses??{};const metrics=audit.metrics;return <>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Score name="Performance" value={audit.performance_score} icon={StatusUp}/><Score name="Accessibility" value={audit.accessibility_score} icon={Activity}/><Score name="Best practices" value={audit.best_practices_score} icon={Cpu}/><Score name="SEO" value={audit.seo_score} icon={Chart}/></div>
  <AuditBalance audit={audit}/>
  <div className="grid gap-4 lg:grid-cols-3"><Vital name="LCP" value={metrics.lcp_ms} unit="ms" status={cwv.LCP} source={audit.metric_sources?.lcp_ms}/><Vital name="INP" value={metrics.inp_ms} unit="ms" status={cwv.INP} source={audit.metric_sources?.inp_ms}/><Vital name="CLS" value={metrics.cls} status={cwv.CLS} source={audit.metric_sources?.cls}/></div>
  <Card><CardHeader><CardTitle>Core Web Vitals budget comparison</CardTitle><CardDescription>Field values use the 75th percentile when PageSpeed supplies CrUX data. Lower is better.</CardDescription></CardHeader><CardContent><WebVitalsChart metrics={metrics}/></CardContent></Card>
  <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Lighthouse lab diagnostics</CardTitle><CardDescription>Controlled lab observations; these are not real-user field measurements.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(audit.lab_metrics??{}).map(([key,value])=><Metric key={key} name={key} value={value}/>)}</CardContent></Card><Card><CardHeader><CardTitle>CrUX field evidence</CardTitle><CardDescription>Real-user page data is preferred; origin data is the fallback.</CardDescription></CardHeader><CardContent className="grid gap-3">{([audit.field_data?.page,audit.field_data?.origin] as const).map((group,index)=><div key={index} className="rounded-xl border p-4"><div className="text-xs font-black uppercase tracking-wide">{index===0?"Page":"Origin"} · {group?.id||"No identifier"}</div><div className="mt-3 flex flex-wrap gap-2">{Object.entries(group?.metrics??{}).length?Object.entries(group?.metrics??{}).map(([name,item])=><span key={name} className="rounded-full bg-[var(--muted)] px-3 py-1.5 text-xs font-bold">{name.replace("_ms","").toUpperCase()}: {item.value??"—"}</span>):<span className="text-sm text-[var(--muted-foreground)]">No field data returned.</span>}</div></div>)}</CardContent></Card></div>
  <Card><CardHeader><CardTitle>Highest-impact Lighthouse opportunities</CardTitle><CardDescription>Ordered by estimated time and byte savings from the imported Lighthouse audit.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{audit.opportunities?.length?audit.opportunities.map((item,index)=><div key={item.id} className="rounded-xl border p-4"><div className="flex items-start gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-indigo-500/10 text-xs font-black text-indigo-600">{index+1}</span><div><div className="font-black">{item.title}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">{item.display_value||`${item.savings_ms} ms · ${Math.round(item.savings_bytes/1024)} KB potential savings`}</div></div></div></div>):<Empty text="No measurable Lighthouse savings opportunities were returned."/>}</CardContent></Card>
  </>}

function AuditBalance({audit}:{audit:Audit}){const scores=[{name:"Performance",score:audit.performance_score},{name:"Accessibility",score:audit.accessibility_score},{name:"Best practices",score:audit.best_practices_score},{name:"SEO",score:audit.seo_score}],ranked=[...scores].sort((a,b)=>(a.score??101)-(b.score??101));return <Card><CardHeader><CardTitle>Audit score balance</CardTitle><CardDescription>A balanced site needs speed, accessibility, implementation quality, and discoverability—not one strong score hiding weaker areas.</CardDescription></CardHeader><CardContent className="grid gap-5 lg:grid-cols-[1fr_.8fr] lg:items-center"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><RadarChart data={scores} outerRadius="72%"><PolarGrid/><PolarAngleAxis dataKey="name" tick={{fontSize:11}}/><Tooltip formatter={value=>[value==null?"Unavailable":`${Number(value)}/100`,"Score"]}/><Radar dataKey="score" stroke="#4f46e5" fill="#6366f1" fillOpacity={.3}/></RadarChart></ResponsiveContainer></div><div className="grid gap-2">{ranked.map((item,index)=><div key={item.name} className="flex items-center justify-between rounded-xl bg-[var(--muted)] p-3 text-sm"><span>{index===0&&item.score!=null?"Priority: ":""}{item.name}</span><strong>{item.score==null?"Unavailable":`${item.score}/100`}</strong></div>)}</div></CardContent></Card>}

function Planned({metrics}:{metrics:Record<string,unknown>}){const allowed=["target_lcp_ms","target_inp_ms","target_cls","initial_js_kb","largest_image_kb","api_p95_ms","target_error_rate"];return <Card><CardHeader><CardTitle>Pre-launch performance budgets</CardTitle><CardDescription>Use these limits in development, CI, and authorized pre-production testing.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{allowed.map(key=><Metric key={key} name={key} value={metrics[key]}/>)}</CardContent></Card>}
function Vital({name,value,unit="",status="UNKNOWN",source}:{name:string;value:unknown;unit?:string;status?:string;source?:string}){return <Card className="card-hover"><CardContent className="p-5 pt-5"><div className="flex items-center justify-between"><div className="text-sm font-black">{name}</div><Status value={status}/></div><div className="mt-4 text-3xl font-black">{value==null?"—":`${String(value)} ${unit}`}</div><div className="mt-2 text-xs text-[var(--muted-foreground)]">{(source||"UNAVAILABLE").replaceAll("_"," ")}</div></CardContent></Card>}
function Score({name,value,icon:Icon}:{name:string;value:number|null;icon:typeof Activity}){return <Card><CardContent className="p-5 pt-5"><Icon className="size-5 text-indigo-500" color="currentColor"/><div className="mt-4 text-xs font-bold text-[var(--muted-foreground)]">{name}</div><div className="mt-1 text-3xl font-black">{value??"—"}<span className="text-sm text-[var(--muted-foreground)]">/100</span></div></CardContent></Card>}
function Metric({name,value}:{name:string;value:unknown}){const shown=value==null?"Unavailable":name.endsWith("_ms")?`${value} ms`:name.endsWith("_kb")?`${value} KB`:name.includes("rate")?`${Number(value)*100}%`:String(value);return <div className="rounded-xl bg-[var(--muted)] p-4"><div className="text-[10px] font-black uppercase tracking-wide text-[var(--muted-foreground)]">{name.replaceAll("_"," ")}</div><div className="mt-2 text-lg font-black">{shown}</div></div>}
function Status({value}:{value:string}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${statusTone[value]||statusTone.UNKNOWN}`}>{value.replaceAll("_"," ")}</span>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-6 text-center text-sm text-[var(--muted-foreground)]">{text}</div>}
function Loading(){return <div className="grid min-h-52 place-items-center"><Loader2 className="size-6 animate-spin text-indigo-500"/></div>}
