"use client";

import {useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {motion} from "framer-motion";
import {Activity,ArrowRight,CheckCircle2,Clock3,Info,Loader2,MousePointerClick,RefreshCw,ShieldCheck,Sparkles,TriangleAlert,Zap} from "lucide-react";
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {toast} from "sonner";
import {projectDataService} from "@/services/project-data-service";
import {projectService} from "@/services/project-service";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Input,Select} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";

type Recommendation={recommended_test_type:string;reason:string;expected_concurrent_users:number;requests_per_user_per_minute:number;estimated_rps:number;peak_rps:number;traffic_classification:string;recommended_target_vus:number;recommended_duration_seconds:number;thresholds:{p95_ms:number;p99_ms:number;error_rate:number;check_pass_rate:number};ai_context:{hosting:string;vcpu:number;ram_gb:number;confidence:number};performance_context?:{available:boolean;source?:string;performance_score:number|null;lcp_ms:number|null;inp_ms:number|null;cls:number|null;tbt_ms:number|null;ttfb_ms:number|null};calculation:{requests_per_minute:number;estimated_rps_formula:string;peak_rps_formula:string};warnings:string[];performance_score:number|null};
type Result={id:string;sourceType:string;overallStatus:string;aiValidationStatus:string;totalRequests:number;peakVus:number;averageRps:number;averageMs:number;p50Ms:number;p90Ms:number;p95Ms:number;p99Ms:number;errorRate:number;checksPassed:number;checksFailed:number;analysis:{reasons?:string[];evidence_note?:string;traffic_coverage?:{status:string;actual_rps:number;expected_rps:number|null;peak_rps:number|null;ratio:number|null};thresholds?:{p95?:{limit_ms:number;actual_ms:number;passed:boolean};error_rate?:{limit:number;actual:number;passed:boolean}}}};
type Plan={id:string;planId:string;testType:string;targetUrl:string;targetVirtualUsers:number;durationSeconds:number;status:string;executionMode:string;thresholds:{p95Ms:number;errorRate:number};warnings:string[];results:Result[];outdated:boolean;createdAt:string};
type ManagedResponse={plan:Plan;result:Result;experience:{executionMode:string;requiresDownload:boolean;requiresUpload:boolean}};
const msg=(e:unknown)=>e&&typeof e==="object"&&"message" in e?String(e.message):"The website test could not be completed.";
const progressSteps=["Checking the website and safety rules","Sending a small, controlled traffic sample","Measuring speed and request failures","Building your easy-to-read report"];

export function LoadTestPanel({projectId}:{projectId:string}){
 const client=useQueryClient();
 const project=useQuery({queryKey:["project",projectId],queryFn:()=>projectService.get(projectId)});
 const rec=useQuery<Recommendation>({queryKey:["load-test-recommendation",projectId],queryFn:()=>projectDataService.loadTestRecommendation(projectId)});
 const history=useQuery<Plan[]>({queryKey:["load-test-history",projectId],queryFn:()=>projectDataService.loadTestHistory(projectId)});
 const [authorized,setAuthorized]=useState(false),[risk,setRisk]=useState(false),[testType,setTestType]=useState("LOAD"),[target,setTarget]=useState(""),[vus,setVus]=useState(5),[paths,setPaths]=useState("/");
 const [active,setActive]=useState<Plan|null>(null),[progress,setProgress]=useState(0),[firstResult,setFirstResult]=useState(""),[secondResult,setSecondResult]=useState("");
 useEffect(()=>{if(project.data&&!target)setTarget(project.data.website||"")},[project.data,target]);
 useEffect(()=>{if(rec.data){setTestType(rec.data.recommended_test_type==="SMOKE"?"SMOKE":"LOAD");setVus(Math.max(1,Math.min(rec.data.recommended_target_vus,10))) }},[rec.data]);
 const run=useMutation<ManagedResponse>({mutationFn:()=>projectDataService.runManagedLoadTest(projectId,{authorization_confirmed:authorized,risk_acknowledged:risk,test_type:testType,target_url:target,target_virtual_users:vus,duration_seconds:60,response_time_threshold_ms:rec.data?.thresholds.p95_ms||2000,error_rate_threshold:rec.data?.thresholds.error_rate||.01,safe_paths:paths.split("\n").map(x=>x.trim()).filter(Boolean)}),onSuccess:async(payload)=>{setActive(payload.plan);await client.invalidateQueries({queryKey:["load-test-history",projectId]});toast.success("Website test complete — your report is ready")},onError:async e=>{await client.invalidateQueries({queryKey:["load-test-history",projectId]});toast.error(`${msg(e)} If the test finished while this page was waiting, refresh the saved-test list below.`)}});
 useEffect(()=>{if(!run.isPending){setProgress(0);return}const timer=window.setInterval(()=>setProgress(value=>Math.min(value+1,progressSteps.length-1)),1800);return()=>window.clearInterval(timer)},[run.isPending]);
 const compare=useMutation({mutationFn:()=>projectDataService.compareLoadTests(projectId,firstResult,secondResult),onError:e=>toast.error(msg(e))});
 const current=active||history.data?.[0];const result=current?.results?.[0];
 const targetReady=target.trim().length>0;const canRun=authorized&&risk&&targetReady&&!run.isPending;
 const runBlockReason=!targetReady?"Enter the public website address to enable testing.":!authorized?"Confirm that you own or are authorized to test this website.":!risk?"Confirm that you understand the small temporary traffic increase.":null;
 const allResults=useMemo(()=>history.data?.flatMap(plan=>(plan.results||[]).map(item=>({item,date:plan.createdAt})))||[],[history.data]);
 const trendData=useMemo(()=>[...allResults].reverse().map(({item,date})=>({date:new Date(date).toLocaleDateString(undefined,{month:"short",day:"numeric"}),p50:item.p50Ms,p95:item.p95Ms,p99:item.p99Ms,error:Number((item.errorRate*100).toFixed(2))})),[allResults]);
 const outcomeData=useMemo(()=>{const counts={Healthy:0,"Needs attention":0,"Action needed":0};allResults.forEach(({item})=>{const label=friendlyStatus(item.overallStatus) as keyof typeof counts;if(label in counts)counts[label]++});return Object.entries(counts).filter(([,value])=>value>0).map(([name,value])=>({name,value}))},[allResults]);
 if(rec.isLoading)return <div className="grid min-h-60 place-items-center"><Loader2 className="size-7 animate-spin text-violet-600"/></div>;
 if(rec.isError)return <Card><CardContent className="p-8">{msg(rec.error)} Complete the project analysis first.</CardContent></Card>;
 const r=rec.data!;
 return <div className="grid gap-5">
  <section className="relative overflow-hidden rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-600/12 via-cyan-500/8 to-emerald-500/10 p-6 sm:p-8">
   <div className="absolute -right-16 -top-20 size-56 rounded-full bg-violet-500/15 blur-3xl"/><div className="relative max-w-3xl"><Badge><Sparkles className="mr-1 size-3"/>Managed for you · Powered by k6</Badge><h2 className="mt-4 text-3xl font-black tracking-tight">Test your website with one click</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">No downloads, terminal commands, scripts, or result files. The server builds a safe k6 scenario, runs it within strict limits, analyses genuine k6 output, saves the evidence, and explains what it means.</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold"><Pill icon={<ShieldCheck/>}>GET-only safety</Pill><Pill icon={<Zap/>}>Up to 10 k6 virtual users</Pill><Pill icon={<Activity/>}>Genuine k6 summary</Pill></div></div>
  </section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Expected visitors at once" value={r.expected_concurrent_users} hint="From your project inputs"/><Metric label="Predicted busiest traffic" value={`${r.peak_rps} req/s`} hint="Used to size this test"/><Metric label="Current performance" value={r.performance_score??"Not measured"} hint="Latest website analysis"/><Metric label="Recommended starting size" value={`${r.ai_context.vcpu} vCPU · ${r.ai_context.ram_gb} GB`} hint={`${r.ai_context.hosting.replaceAll("_"," ")} · ${Math.round((r.ai_context.confidence||0)*100)}% confidence`}/></div>
  <div className="grid gap-4 lg:grid-cols-2"><Card className="border-cyan-500/25"><CardHeader><CardTitle>PageSpeed and Lighthouse</CardTitle><CardDescription>Frontend and user-experience quality before load is applied.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-3"><MiniMetric label="Performance" value={r.performance_context?.performance_score==null?"Unavailable":`${r.performance_context.performance_score}/100`}/><MiniMetric label="LCP" value={r.performance_context?.lcp_ms==null?"Unavailable":`${Math.round(r.performance_context.lcp_ms)} ms`}/><MiniMetric label="INP" value={r.performance_context?.inp_ms==null?"Unavailable":`${Math.round(r.performance_context.inp_ms)} ms`}/><MiniMetric label="CLS" value={r.performance_context?.cls??"Unavailable"}/><MiniMetric label="TBT" value={r.performance_context?.tbt_ms==null?"Unavailable":`${Math.round(r.performance_context.tbt_ms)} ms`}/><MiniMetric label="Source" value={r.performance_context?.source??"Workload only"}/></CardContent></Card><Card className="border-violet-500/25"><CardHeader><CardTitle>k6 server-load evidence</CardTitle><CardDescription>Simulated traffic measures response latency, throughput, failures, and checks.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm"><div className="rounded-xl bg-[var(--muted)] p-3"><strong>Scenario source:</strong> {r.expected_concurrent_users} expected users · {r.estimated_rps} expected RPS · {r.peak_rps} peak RPS</div><div className="rounded-xl bg-[var(--muted)] p-3"><strong>AI context:</strong> {r.ai_context.hosting.replaceAll("_"," ")} · {r.ai_context.vcpu} vCPU · {r.ai_context.ram_gb} GB RAM</div><p className="text-xs text-[var(--muted-foreground)]">PageSpeed does not measure server capacity under concurrency. k6 does not measure browser rendering or Core Web Vitals. The report keeps both evidence types separate and considers them together.</p></CardContent></Card></div>
  <div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
   <Card><CardHeader><CardTitle className="flex items-center gap-2"><MousePointerClick className="size-5 text-violet-600"/>Choose what to test</CardTitle><CardDescription>We have already filled in safe starting values from your traffic and AI recommendation.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Website address"><Input aria-invalid={!targetReady} value={target} onChange={e=>setTarget(e.target.value)} placeholder="https://example.com"/>{!targetReady&&<span className="text-xs font-normal text-amber-700 dark:text-amber-300">A public URL is required before the test can start. Planned projects do not have one automatically.</span>}</Field><Field label="Test intensity"><Select value={testType} onChange={e=>setTestType(e.target.value)}><option value="SMOKE">Quick check</option><option value="LOAD">Normal traffic check</option></Select></Field><Field label="Simulated visitors at once"><Input type="number" min={1} max={10} value={vus} onChange={e=>setVus(Math.max(1,Math.min(10,+e.target.value||1)))}/><span className="text-xs font-normal text-[var(--muted-foreground)]">Automatically limited to 10 for safety.</span></Field><Field label="Public pages to check"><textarea className="min-h-20 rounded-xl border bg-transparent px-3 py-2 font-normal" value={paths} onChange={e=>setPaths(e.target.value)} placeholder={"/\n/pricing\n/about"}/><span className="text-xs font-normal text-[var(--muted-foreground)]">One safe page path per line. Leave / to test the home page.</span></Field></CardContent></Card>
   <Card className="border-emerald-500/25"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-600"/>Permission and safety</CardTitle><CardDescription>These checks protect both you and the website.</CardDescription></CardHeader><CardContent className="grid gap-3"><Check checked={authorized} set={setAuthorized}>I own this website or have clear permission to test it.</Check><Check checked={risk} set={setRisk}>I understand this creates a small, temporary increase in website traffic.</Check><Button size="lg" className="mt-2 w-full" disabled={!canRun} onClick={()=>run.mutate()}>{run.isPending?<Loader2 className="size-4 animate-spin"/>:<Activity className="size-4"/>}{run.isPending?"Testing your website…":"Run test and create report"}</Button>{runBlockReason&&<p className="rounded-xl bg-amber-500/10 px-3 py-2 text-center text-xs font-medium text-amber-800 dark:text-amber-200">{runBlockReason}</p>}<p className="text-center text-xs text-[var(--muted-foreground)]">Only public pages on this website are requested. Private networks, unsafe ports, account actions, payments, and destructive paths are blocked.</p></CardContent></Card>
  </div>
  {run.isPending&&<Card className="overflow-hidden border-violet-500/30"><motion.div className="h-1 bg-gradient-to-r from-violet-600 via-cyan-500 to-emerald-500" initial={{width:"10%"}} animate={{width:`${25+progress*24}%`}}/><CardContent className="p-6"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-violet-600/10"><Loader2 className="size-5 animate-spin text-violet-600"/></div><div><strong>{progressSteps[progress]}</strong><p className="text-sm text-[var(--muted-foreground)]">A normal test takes about one minute. Keep this page open while k6 completes and saves your report.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-4">{progressSteps.map((step,index)=><div key={step} className={`rounded-xl p-3 text-xs ${index<=progress?"bg-violet-600/10 text-violet-700 dark:text-violet-300":"bg-[var(--muted)] text-[var(--muted-foreground)]"}`}>{index<progress?<CheckCircle2 className="mb-2 size-4"/>:<Clock3 className="mb-2 size-4"/>}{step}</div>)}</div></CardContent></Card>}
  {result&&current&&<ResultEvidence result={result} plan={current}/>}
  {trendData.length>0&&<div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><CardTitle>Website response trend</CardTitle><CardDescription>Typical, p95, and slowest-request timing across automatically saved tests. Lower is better.</CardDescription></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={trendData}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="date"/><YAxis unit=" ms"/><Tooltip/><Legend/><Line type="monotone" dataKey="p50" name="Typical" stroke="#06b6d4" strokeWidth={2}/><Line type="monotone" dataKey="p95" name="95%" stroke="#7c3aed" strokeWidth={3}/><Line type="monotone" dataKey="p99" name="Slowest" stroke="#f59e0b" strokeWidth={2}/></LineChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Result health mix</CardTitle><CardDescription>How often saved tests met speed, reliability, and response checks.</CardDescription></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={outcomeData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} paddingAngle={3} label>{outcomeData.map((entry,index)=><Cell key={entry.name} fill={["#10b981","#f59e0b","#ef4444"][index]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></CardContent></Card></div>}
  <Card><CardHeader><CardTitle>Past website tests</CardTitle><CardDescription>Every completed report is saved automatically. Select one to review it again.</CardDescription></CardHeader><CardContent>{history.data?.length?<div className="grid gap-2">{history.data.map(plan=>{const item=plan.results?.[0];return <button type="button" onClick={()=>setActive(plan)} key={plan.id} className="grid w-full gap-2 rounded-2xl border p-4 text-left transition hover:border-violet-500/40 hover:bg-violet-500/5 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><div><strong>{new Date(plan.createdAt).toLocaleString()}</strong><div className="text-xs text-[var(--muted-foreground)]">{plan.targetUrl}</div></div><Badge>{item?friendlyStatus(item.overallStatus):"Incomplete"}</Badge><span className="text-sm">{item?`${Math.round(item.p95Ms)} ms p95`:"No report"}</span><ArrowRight className="size-4 text-[var(--muted-foreground)]"/></button>})}</div>:<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-[var(--muted-foreground)]">No tests yet. Confirm permission above and run your first safe test.</div>}</CardContent></Card>
  {allResults.length>=2&&<Card><CardHeader><CardTitle>Did the website improve?</CardTitle><CardDescription>Compare two saved reports to see the change in speed, failures, and request handling.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><Select value={firstResult} onChange={e=>setFirstResult(e.target.value)}><option value="">Choose earlier test</option>{allResults.map(({item,date})=><option key={item.id} value={item.id}>{new Date(date).toLocaleDateString()} · {Math.round(item.p95Ms)} ms</option>)}</Select><Select value={secondResult} onChange={e=>setSecondResult(e.target.value)}><option value="">Choose newer test</option>{allResults.map(({item,date})=><option key={item.id} value={item.id}>{new Date(date).toLocaleDateString()} · {Math.round(item.p95Ms)} ms</option>)}</Select><Button disabled={!firstResult||!secondResult||firstResult===secondResult||compare.isPending} onClick={()=>compare.mutate()}>{compare.isPending?<Loader2 className="size-4 animate-spin"/>:<RefreshCw className="size-4"/>}Compare</Button></div>{compare.data&&<div className="grid gap-3 sm:grid-cols-3"><Metric label="Speed improvement" value={compare.data.p95.improvementPercent==null?"Not available":`${compare.data.p95.improvementPercent}%`}/><Metric label="Failure improvement" value={compare.data.errorRate.improvementPercent==null?"Not available":`${compare.data.errorRate.improvementPercent}%`}/><Metric label="Requests/second change" value={compare.data.rps.difference?.toFixed(2)??"Not available"}/></div>}</CardContent></Card>}
  <Card><CardContent className="flex gap-3 p-5 text-sm"><Info className="size-5 shrink-0 text-cyan-600"/><div><strong>How to read this:</strong> p95 is the time in which 95 out of 100 requests finished. A lower number is faster. Failure rate is the share of requests that did not return a usable response. This is a safe public-page sample, not a destructive stress test.</div></CardContent></Card>
 </div>
}

function ResultEvidence({result,plan}:{result:Result;plan:Plan}){const threshold=plan.thresholds?.p95Ms||2000;const chart=[{name:"Typical",value:result.p50Ms},{name:"90%",value:result.p90Ms},{name:"95%",value:result.p95Ms},{name:"Slowest",value:result.p99Ms}];const passed=result.overallStatus==="PASS",coverage=result.analysis?.traffic_coverage;return <Card className={passed?"border-emerald-500/35":"border-amber-500/35"}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2">{passed?<CheckCircle2 className="size-6 text-emerald-600"/>:<TriangleAlert className="size-6 text-amber-600"/>}Your genuine k6 report</CardTitle><CardDescription>{result.sourceType==="K6_MANAGED_SUMMARY"?"Generated directly from the server-managed k6 summary output.":"Generated from imported k6 evidence."}</CardDescription></div><Badge>{friendlyStatus(result.overallStatus)}</Badge></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Requests checked" value={result.totalRequests}/><Metric label="k6 virtual users" value={result.peakVus}/><Metric label="95% finished within" value={`${Math.round(result.p95Ms)} ms`}/><Metric label="Request failures" value={`${(result.errorRate*100).toFixed(2)}%`}/><Metric label="Average throughput" value={`${result.averageRps?.toFixed(1)} req/s`}/><Metric label="Traffic coverage" value={coverage?.status?.replaceAll("_"," ")??"Unavailable"}/></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div><h3 className="mb-2 font-bold">Response-time distribution</h3><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="name"/><YAxis unit=" ms"/><Tooltip formatter={(value)=>[`${Math.round(Number(value))} ms`,"Response time"]}/><ReferenceLine y={threshold} stroke="#ef4444" strokeDasharray="5 5" label="Target"/><Bar dataKey="value" fill="#7c3aed" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="grid content-start gap-3"><h3 className="font-bold">What this means</h3>{coverage&&<div className="rounded-xl border border-violet-500/20 bg-violet-500/8 p-3 text-sm">k6 produced {coverage.actual_rps.toFixed(2)} RPS against an expected {coverage.expected_rps?.toFixed(2)??"unknown"} RPS. Coverage: <strong>{coverage.status.replaceAll("_"," ")}</strong>.</div>}{result.analysis?.reasons?.length?result.analysis.reasons.map(reason=><div className="rounded-xl bg-amber-500/10 p-3 text-sm" key={reason}>{plainReason(reason)}</div>):<div className="rounded-xl bg-emerald-500/10 p-3 text-sm">The tested pages stayed within the speed target and returned successful responses during this sample.</div>}<div className="rounded-xl bg-[var(--muted)] p-3 text-xs text-[var(--muted-foreground)]">{result.analysis?.evidence_note}</div></div></div></CardContent></Card>}
function friendlyStatus(status:string){return status==="PASS"?"Healthy":status==="PARTIAL_PASS"?"Needs attention":status==="FAIL"?"Action needed":status.replaceAll("_"," ")}
function plainReason(reason:string){return reason.replaceAll("p95 response time","The 95% response time").replaceAll("VUs","simulated visitors")}
function Pill({icon,children}:{icon:React.ReactElement;children:React.ReactNode}){return <span className="flex items-center gap-1.5 rounded-full border bg-background/70 px-3 py-1.5 [&_svg]:size-3.5">{icon}{children}</span>}
function Metric({label,value,hint}:{label:string;value:string|number|undefined;hint?:string}){return <Card><CardContent className="p-4"><div className="text-xs text-[var(--muted-foreground)]">{label}</div><div className="mt-1 text-xl font-black">{value??"—"}</div>{hint&&<div className="mt-1 text-xs text-[var(--muted-foreground)]">{hint}</div>}</CardContent></Card>}
function MiniMetric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-[var(--muted)] p-3"><div className="text-[10px] font-black uppercase tracking-wide text-[var(--muted-foreground)]">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid content-start gap-1.5 text-sm font-semibold">{label}{children}</label>}
function Check({checked,set,children}:{checked:boolean;set:(v:boolean)=>void;children:React.ReactNode}){return <label className={`flex cursor-pointer gap-3 rounded-xl border p-4 transition ${checked?"border-emerald-500/40 bg-emerald-500/8":"hover:bg-[var(--muted)]"}`}><input className="mt-1 accent-emerald-600" type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><strong className="text-sm leading-5">{children}</strong></label>}
