"use client";

import { Graph } from "reicon-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type PerformancePoint={date:string;performance:number|null};
type CostPoint={id:string;recorded_at:string;project_id:string;project_name:string;current:number|null;recommended:number;recommended_min:number|null;recommended_max:number|null;currency:"USD"};
type CoveragePoint={section:string;complete:boolean;count:number;note:string};
type FactorPoint={factor:string;score:number;value:string;effect:string};

const axis={tickLine:false,axisLine:false,tick:{fill:"var(--muted-foreground)",fontSize:12}};
const grid={stroke:"var(--border)",strokeDasharray:"4 6",vertical:false};
const tooltipStyle={contentStyle:{background:"var(--card)",border:"1px solid var(--border)",borderRadius:14,boxShadow:"0 18px 45px var(--shadow)",backdropFilter:"blur(16px)",fontSize:12},labelStyle:{color:"var(--foreground)",fontWeight:800,marginBottom:6},itemStyle:{fontWeight:700},cursor:{fill:"color-mix(in srgb, var(--primary) 7%, transparent)"}};

function Frame({children,label,height="h-72"}:{children:React.ReactNode;label:string;height?:string}){return <div className={`relative ${height}`} role="img" aria-label={label}><div className="pointer-events-none absolute inset-x-8 top-4 h-24 rounded-full bg-gradient-to-r from-indigo-500/10 via-cyan-500/10 to-violet-500/10 blur-3xl"/>{children}</div>}

export function PerformanceChart({data=[]}:{data?:PerformancePoint[]}){const rows=data.map(x=>({...x,date:new Date(x.date).toLocaleDateString()}));return rows.length?<Frame label="Performance score trend over time"><ResponsiveContainer width="100%" height="100%"><LineChart accessibilityLayer data={rows} margin={{top:14,right:12,left:-12,bottom:4}}><defs><linearGradient id="performanceLine" x1="0" y1="0" x2="1" y2="0"><stop stopColor="var(--chart-1)"/><stop offset=".55" stopColor="var(--chart-2)"/><stop offset="1" stopColor="var(--chart-3)"/></linearGradient></defs><CartesianGrid {...grid}/><XAxis dataKey="date" {...axis}/><YAxis domain={[0,100]} {...axis}/><Tooltip {...tooltipStyle}/><Line type="monotone" dataKey="performance" name="Performance" stroke="url(#performanceLine)" strokeWidth={3.5} dot={{r:4,fill:"var(--card)",stroke:"var(--chart-1)",strokeWidth:2}} activeDot={{r:7,fill:"var(--chart-2)",stroke:"var(--card)",strokeWidth:3}} animationDuration={950}/></LineChart></ResponsiveContainer></Frame>:<EmptyChart/>}

export function CostChart({data=[]}:{data?:CostPoint[]}){return data.length?<Frame label="Persisted monthly hosting cost updates over time"><ResponsiveContainer width="100%" height="100%"><AreaChart accessibilityLayer data={data} margin={{top:14,right:12,left:-12,bottom:4}}><defs><linearGradient id="costCurrent" x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--chart-4)" stopOpacity={.42}/><stop offset="1" stopColor="var(--chart-4)" stopOpacity={.02}/></linearGradient><linearGradient id="costRecommended" x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--chart-5)" stopOpacity={.35}/><stop offset="1" stopColor="var(--chart-5)" stopOpacity={.01}/></linearGradient></defs><CartesianGrid {...grid}/><XAxis dataKey="recorded_at" {...axis} tickFormatter={value=>new Date(String(value)).toLocaleDateString(undefined,{month:"short",day:"numeric"})}/><YAxis {...axis}/><Tooltip {...tooltipStyle} labelFormatter={value=>new Date(String(value)).toLocaleString()} formatter={(value,name,item)=>[`USD ${Number(value).toFixed(2)}`,`${name} · ${item.payload.project_name}`]}/><Legend iconType="circle"/><Area connectNulls type="monotone" dataKey="current" name="Current supplied cost" stroke="var(--chart-4)" fill="url(#costCurrent)" strokeWidth={2.5} animationDuration={900}/><Area type="monotone" dataKey="recommended" name="Recommended midpoint" stroke="var(--chart-5)" fill="url(#costRecommended)" strokeWidth={2.5} animationDuration={1100}/></AreaChart></ResponsiveContainer></Frame>:<EmptyChart text="Cost history becomes available after a completed analysis creates a stored USD recommendation."/>}

export function HostingDistribution({data}:{data?:Record<string,number>}){const colors=["var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-4)"];const rows=Object.entries(data??{}).filter(([,value])=>value>0).map(([name,value],i)=>({name:name.replaceAll("_"," "),value,color:colors[i%colors.length]}));return rows.length?<Frame label="Distribution of hosting recommendations"><ResponsiveContainer width="100%" height="100%"><PieChart accessibilityLayer><Pie data={rows} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={4} cornerRadius={6} stroke="var(--card)" strokeWidth={3} animationDuration={1000}>{rows.map(v=><Cell key={v.name} fill={v.color}/>)}</Pie><Tooltip {...tooltipStyle}/><Legend iconType="circle"/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-[62%] text-center"><div className="text-2xl font-black">{rows.reduce((sum,row)=>sum+row.value,0)}</div><div className="text-[10px] font-bold uppercase tracking-wider text-[var(--muted-foreground)]">Decisions</div></div></Frame>:<EmptyChart text="No completed recommendations yet."/>}

export function WorkloadChart({average=0,peak=0}:{average?:number;peak?:number}){const data=[{stage:"Average",requests:average,fill:"var(--chart-2)"},{stage:"Business peak",requests:peak,fill:"var(--chart-1)"},{stage:"Growth +30%",requests:Math.round(peak*1.3),fill:"var(--chart-3)"}];return <Frame label="Estimated workload under average, peak, and growth conditions"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={data} margin={{top:14,right:12,left:-12,bottom:4}}><CartesianGrid {...grid}/><XAxis dataKey="stage" {...axis}/><YAxis {...axis}/><Tooltip {...tooltipStyle} formatter={value=>[`${value} req/s`,"Requests"]}/><Bar dataKey="requests" radius={[10,10,3,3]} animationDuration={900}>{data.map(item=><Cell key={item.stage} fill={item.fill}/>)}</Bar></BarChart></ResponsiveContainer></Frame>}

export function AnalysisCoverageChart({data=[]}:{data?:CoveragePoint[]}){const rows=data.map(item=>({...item,coverage:item.complete?100:item.count?50:10}));return rows.length?<Frame label="Completion coverage for every analysis section" height="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={rows} layout="vertical" margin={{top:8,left:18,right:26,bottom:4}}><CartesianGrid stroke="var(--border)" strokeDasharray="4 6" horizontal={false}/><XAxis type="number" domain={[0,100]} hide/><YAxis type="category" dataKey="section" width={96} {...axis}/><Tooltip {...tooltipStyle} formatter={(value,name,item)=>[`${value}% · ${item.payload.note}`,name]}/><Bar dataKey="coverage" name="Coverage" radius={[0,10,10,0]} animationDuration={900}>{rows.map((item,index)=><Cell key={item.section} fill={item.complete?["var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-5)"][index%4]:"var(--chart-4)"}/>)}</Bar></BarChart></ResponsiveContainer></Frame>:<EmptyChart text="Analysis coverage is not available."/>}

export function DecisionFactorsChart({data=[]}:{data?:FactorPoint[]}){return data.length?<Frame label="Influence scores used to make the hosting decision" height="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={data} margin={{top:14,right:12,left:-12,bottom:4}}><defs><linearGradient id="factorBars" x1="0" y1="1" x2="0" y2="0"><stop stopColor="var(--chart-1)"/><stop offset="1" stopColor="var(--chart-2)"/></linearGradient></defs><CartesianGrid {...grid}/><XAxis dataKey="factor" {...axis}/><YAxis domain={[0,100]} {...axis}/><Tooltip {...tooltipStyle} formatter={(value,name,item)=>[`${value}/100 · ${item.payload.value}`,name]}/><Bar dataKey="score" name="Influence score" fill="url(#factorBars)" radius={[10,10,3,3]} animationDuration={1050}/></BarChart></ResponsiveContainer></Frame>:<EmptyChart text="Decision factors are not available."/>}

export function RecommendationComparisonChart({data=[]}:{data?:Array<Record<string,unknown>>}){const rows=data.map((item,index)=>({option:String(item.display_name??item.option??item.type??"Option").replaceAll("_"," "),score:Number(item.score??item.fitScore??0),fill:["var(--chart-1)","var(--chart-2)","var(--chart-3)"][index%3]}));return rows.length?<Frame label="Fit-score comparison of hosting alternatives"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={rows} margin={{top:14,right:12,left:-12,bottom:4}}><CartesianGrid {...grid}/><XAxis dataKey="option" {...axis}/><YAxis domain={[0,100]} {...axis}/><Tooltip {...tooltipStyle} formatter={value=>[`${value}/100`,`Fit score`]}/><Bar dataKey="score" radius={[10,10,3,3]} animationDuration={950}>{rows.map(item=><Cell key={item.option} fill={item.fill}/>)}</Bar></BarChart></ResponsiveContainer></Frame>:<EmptyChart text="Alternative scores are unavailable."/>}

export function CostBreakdownChart({data=[]}:{data?:Array<{name:string;min:number;max:number;share:number}>}){return data.length?<Frame label="Minimum and maximum monthly cost by infrastructure component"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={data} margin={{top:14,right:12,left:-12,bottom:18}}><CartesianGrid {...grid}/><XAxis dataKey="name" {...axis} interval={0} angle={-10} textAnchor="end" height={54}/><YAxis {...axis}/><Tooltip {...tooltipStyle} formatter={(value,name)=>[`USD ${value}`,name]}/><Legend iconType="circle"/><Bar dataKey="min" name="Minimum" fill="var(--chart-2)" radius={[7,7,2,2]} animationDuration={850}/><Bar dataKey="max" name="Maximum" fill="var(--chart-4)" radius={[7,7,2,2]} animationDuration={1050}/></BarChart></ResponsiveContainer></Frame>:<EmptyChart text="Cost components are unavailable."/>}

export function OptimizationChart({data=[]}:{data?:Array<{priority:string;status:string}>}){const levels=["Critical","High","Medium","Low"];const rows=levels.map(priority=>({priority,open:data.filter(x=>x.priority===priority&&x.status!=="Done").length,done:data.filter(x=>x.priority===priority&&x.status==="Done").length})).filter(x=>x.open+x.done);return rows.length?<Frame label="Open and completed optimizations grouped by priority"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={rows} margin={{top:14,right:12,left:-12,bottom:4}}><CartesianGrid {...grid}/><XAxis dataKey="priority" {...axis}/><YAxis allowDecimals={false} {...axis}/><Tooltip {...tooltipStyle}/><Legend iconType="circle"/><Bar dataKey="open" name="Open" stackId="status" fill="var(--chart-4)" animationDuration={850}/><Bar dataKey="done" name="Done" stackId="status" fill="var(--chart-5)" radius={[8,8,2,2]} animationDuration={1050}/></BarChart></ResponsiveContainer></Frame>:<EmptyChart text="Optimization status data is unavailable."/>}

export function WebVitalsChart({metrics={}}:{metrics?:Record<string,unknown>}){const definitions=[{name:"LCP",key:"lcp_ms",target:2500},{name:"INP",key:"inp_ms",target:200},{name:"CLS",key:"cls",target:.1},{name:"FCP",key:"fcp_ms",target:1800},{name:"TBT",key:"tbt_ms",target:200},{name:"Speed Index",key:"speed_index_ms",target:3400}];const rows=definitions.filter(item=>typeof metrics[item.key]==="number").map(item=>({metric:item.name,budget:100,observed:Math.round((Number(metrics[item.key])/item.target)*100),raw:Number(metrics[item.key]),target:item.target}));return rows.length?<Frame label="Observed Core Web Vitals compared with target budgets"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={rows} margin={{top:14,right:12,left:-12,bottom:4}}><CartesianGrid {...grid}/><XAxis dataKey="metric" {...axis}/><YAxis {...axis}/><Tooltip {...tooltipStyle} formatter={(value,name,item)=>name==="Observed"?[`${value}% of budget · ${item.payload.raw} / ${item.payload.target}`,name]:[`${value}%`,name]}/><Legend iconType="circle"/><Bar dataKey="budget" name="Target budget" fill="var(--muted-foreground)" fillOpacity={.25} radius={[7,7,2,2]}/><Bar dataKey="observed" name="Observed" radius={[7,7,2,2]} animationDuration={1000}>{rows.map(item=><Cell key={item.metric} fill={item.observed<=100?"var(--chart-5)":item.observed<=150?"var(--chart-4)":"var(--chart-6)"}/>)}</Bar></BarChart></ResponsiveContainer></Frame>:<EmptyChart text="Measured Core Web Vitals are unavailable for this mode."/>}

function EmptyChart({text="No performance history yet."}:{text?:string}){return <div className="tech-grid grid h-72 place-items-center rounded-2xl border border-dashed text-center"><div className="max-w-xs"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500/15 to-cyan-500/15 text-indigo-600 dark:text-indigo-300"><Graph className="size-6" color="currentColor"/></span><p className="mt-3 text-sm font-medium text-[var(--muted-foreground)]">{text}</p></div></div>}
