"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { ArrowRight, BrainCircuit, CheckCircle2, CircleDollarSign, Database, Gauge, Globe2, Layers3, LockKeyhole, Radar, Rocket, Server, ShieldCheck, Sparkles, WandSparkles, type LucideIcon } from "lucide-react";
import { PublicNav } from "@/components/public/public-nav";
import { Card, CardContent } from "@/components/ui/card";

const steps=[
  {icon:Globe2,title:"Share your situation",text:"Begin with a live URL, a planned website, or a fresh product idea.",note:"The advisor captures project context: traffic, budget, reliability, growth and technology choices.",href:"#knowledge"},
  {icon:Radar,title:"Watch the system inspect",text:"Performance, traffic, capacity, and cost evidence are organized into one view.",note:"It combines PageSpeed-style performance evidence with workload estimates and stored cost ranges.",href:"#features"},
  {icon:BrainCircuit,title:"Reveal the model decision",text:"The trained classifier predicts VPS, Cloud VM, or Kubernetes from your input.",note:"The model probability decides the recommendation. Cost and AI explanations clarify it but never override it.",href:"#recommendation"},
];

export default function Landing(){
  const [activeStep,setActiveStep]=useState(0);
  return <div className="landing-shell"><PublicNav/><main id="home">
    <section className="landing-hero relative isolate flex items-center overflow-hidden">
      <div className="hero-grid absolute inset-0 opacity-70"/>
      <div className="signal-orb absolute -right-20 top-8 size-72 rounded-full border border-[var(--primary)]/25"/>
      <div className="signal-orb absolute -left-28 bottom-0 size-80 rounded-full border border-[var(--secondary)]/20 [animation-direction:reverse]"/>
      <div className="relative mx-auto grid w-full max-w-7xl items-center gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
        <div className="max-w-3xl">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border bg-[var(--card)] px-3 py-1.5 text-xs font-black uppercase tracking-[.12em] text-[var(--primary)]"><Sparkles className="size-3.5"/>Hosting decisions, made visible</div>
          <h1 className="text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Know what your infrastructure <span className="gradient-text">actually needs.</span></h1>
          <p className="mt-6 max-w-2xl text-base leading-8 text-[var(--muted-foreground)] sm:text-lg">A friendly AI workspace that translates your traffic, performance, budget and growth plans into an evidence-backed hosting recommendation.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#knowledge" className="inline-flex h-11 items-center justify-center rounded-xl bg-gradient-to-r from-[var(--primary)] via-[var(--secondary)] to-[var(--accent)] px-5 text-sm font-black text-[var(--primary-foreground)] shadow-lg transition hover:-translate-y-0.5">Explore the advisor <ArrowRight className="ml-2 size-4"/></a><a href="#how" className="inline-flex h-11 items-center justify-center rounded-xl border px-5 text-sm font-bold transition hover:bg-[var(--muted)]">See how it works</a></div>
          <div className="mt-9 grid gap-3 text-sm text-[var(--muted-foreground)] sm:grid-cols-3"><Proof text="Model-first decision"/><Proof text="Costs shown honestly"/><Proof text="Safe testing workflow"/></div>
        </div>
        <RobotScene/>
      </div>
    </section>

    <section id="features" className="mx-auto max-w-7xl px-4 py-20 sm:px-6">
      <div className="max-w-2xl"><span className="text-xs font-black uppercase tracking-[.18em] text-[var(--primary)]">One connected workspace</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Every useful signal, without the infrastructure jargon.</h2></div>
      <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Feature icon={Globe2} title="Technology signals" text="Surface likely frameworks, CMS, CDN and hosting evidence."/><Feature icon={Gauge} title="Performance clarity" text="Turn Lighthouse-style metrics into practical next actions."/><Feature icon={Layers3} title="Workload picture" text="Translate people, requests, data and growth into capacity context."/><Feature icon={BrainCircuit} title="Unbiased prediction" text="The trained classifier selects only from its own probabilities."/><Feature icon={CircleDollarSign} title="Cost explorer" text="Compare transparent stored ranges without pretending prices are exact."/><Feature icon={ShieldCheck} title="Guided load testing" text="Run authorized, GET-only checks with a plain-language report."/></div>
    </section>

    <section id="how" className="border-y bg-[var(--card)]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div className="max-w-2xl"><span className="text-xs font-black uppercase tracking-[.18em] text-[var(--primary)]">A live walkthrough</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Tap a stage. See what the advisor is doing.</h2></div><div className="rounded-full border bg-[var(--background)] px-4 py-2 text-xs font-bold text-[var(--muted-foreground)]">Interactive by design</div></div>
      <div className="mt-10 grid gap-4 lg:grid-cols-3">{steps.map((step,index)=><HowStep key={step.title} {...step} index={index} active={activeStep===index} onActivate={()=>setActiveStep(index)}/>)}</div>
    </div></section>

    <section id="recommendation" className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
      <div><span className="text-xs font-black uppercase tracking-[.18em] text-[var(--primary)]">Prediction reveal</span><h2 className="mt-3 text-4xl font-black tracking-tight">Your next hosting choice should feel like a reveal, not a sales pitch.</h2><p className="mt-5 max-w-xl leading-7 text-[var(--muted-foreground)]">No option starts ahead. Your answers become model features; the highest Logistic Regression probability becomes the recommendation. Cost, resource sizing and AI explanations add context but never change it.</p><div className="mt-7 grid gap-3"><Proof text="VPS, Cloud VM and Kubernetes are equal candidates"/><Proof text="The current input drives every prediction"/><Proof text="Recalculate anytime after changing your plan"/></div></div>
      <PredictionPanel/>
    </div></section>

    <section id="knowledge" className="border-y bg-[var(--card)]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="mx-auto max-w-3xl text-center"><span className="text-xs font-black uppercase tracking-[.18em] text-[var(--primary)]">What this project actually does</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">From a website question to a decision you can explain.</h2><p className="mt-4 leading-7 text-[var(--muted-foreground)]">AI Hosting Advisor is not a hosting seller. It is a decision-support workspace that turns evidence into a readable infrastructure plan.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Knowledge icon={Globe2} title="1. Understand" text="Collect a public URL or project requirements and keep your assumptions visible."/><Knowledge icon={Gauge} title="2. Measure" text="Review performance, Core Web Vitals-style metrics and workload capacity signals."/><Knowledge icon={BrainCircuit} title="3. Predict" text="Use the trained Logistic Regression model to select one unbiased hosting option."/><Knowledge icon={CircleDollarSign} title="4. Plan" text="Compare stored price ranges, resource size, optimizations and safe test results."/></div></div></section>

    <section className="border-y bg-[var(--card)]"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="text-xs font-black uppercase tracking-[.18em] text-[var(--primary)]">Built for follow-through</span><h2 className="mt-3 text-3xl font-black">A recommendation you can revisit, explain, and improve.</h2><p className="mt-3 max-w-2xl leading-7 text-[var(--muted-foreground)]">Keep project history, performance evidence, cost ranges and test results in one accountable workspace.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[[Database,"Saved evidence"],[LockKeyhole,"Private workspace"],[Gauge,"Performance"],[Server,"Cost context"]].map(([Icon,label])=>{const I=Icon as LucideIcon;return <div key={String(label)} className="rounded-2xl border bg-[var(--background)] p-4 text-center"><I className="mx-auto size-5 text-[var(--primary)]"/><div className="mt-2 text-xs font-bold">{String(label)}</div></div>})}</div></div></section>
  </main><Footer/></div>;
}

function RobotScene(){const [look,setLook]=useState({x:0,y:0});return <div onMouseMove={event=>{const box=event.currentTarget.getBoundingClientRect();setLook({x:Math.round((event.clientX-box.left)/box.width*12-6),y:Math.round((event.clientY-box.top)/box.height*10-5)})}} onMouseLeave={()=>setLook({x:0,y:0})} className="relative mx-auto w-full max-w-md overflow-hidden rounded-[2.25rem] border bg-[var(--card)] p-5 shadow-2xl shadow-[var(--shadow)]"><div className="absolute inset-0"><div className="signal-orb absolute -right-12 -top-12 size-40 rounded-full border border-[var(--primary)]/30"/><div className="signal-orb absolute -bottom-14 -left-10 size-48 rounded-full border border-[var(--secondary)]/25 [animation-direction:reverse]"/></div><div className="relative rounded-[1.7rem] border bg-[var(--background)] p-5"><div className="flex items-center justify-between text-xs font-black uppercase tracking-[.14em] text-[var(--muted-foreground)]"><span>Advisor scan</span><span className="live-dot size-2 rounded-full bg-[var(--primary)]"/></div><div className="relative mx-auto mt-2 h-[340px] sm:h-[390px]"><div className="absolute inset-x-7 bottom-6 h-10 rounded-[100%] bg-[var(--secondary)]/15 blur-xl"/><Image src="/brand/advisor-robot.png" alt="Animated AI advisor robot scanning the page" width={1024} height={1536} priority className="robot relative z-10 mx-auto h-full w-auto object-contain drop-shadow-2xl transition-transform duration-200" style={{transform:`translate(${look.x}px, ${look.y}px) rotate(${look.x*.35}deg)`}}/><div className="pointer-events-none absolute inset-x-5 top-1/2 h-px bg-[var(--primary)]/60 shadow-[0_0_20px_var(--primary)]"/></div><div className="mt-2 grid grid-cols-3 gap-2 text-center text-[10px] font-bold"><Scan label="Traffic" value="Read"/><Scan label="Signals" value="Linked"/><Scan label="Model" value="Ready"/></div></div><p className="relative mt-4 text-center text-sm font-bold">Move around me — I’m scanning your signals.</p></div>}
function PredictionPanel(){return <div className="prediction-card relative overflow-hidden rounded-[2rem] border p-6 sm:p-8"><div className="prediction-sweep pointer-events-none absolute inset-y-0 w-1/3 bg-gradient-to-r from-transparent via-white/50 to-transparent"/><div className="relative"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[var(--primary)]">Prediction guide</p><h3 className="mt-2 text-2xl font-black">What the model compares</h3></div><span className="grid size-12 place-items-center rounded-2xl bg-[var(--primary)] text-[var(--primary-foreground)]"><BrainCircuit className="size-6"/></span></div><div className="mt-7 rounded-2xl border bg-[var(--background)] p-4"><div className="flex items-center justify-between text-sm font-bold"><span>Input signal</span><span className="text-[var(--primary)]">Traffic + budget + growth</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[var(--muted)]"><div className="h-full w-2/3 rounded-full bg-[var(--primary)]"/></div><p className="mt-3 text-sm leading-6 text-[var(--muted-foreground)]">It uses practical context such as expected visitors, concurrent users, peak requests, storage, availability and operational needs.</p></div><div className="mt-4 grid grid-cols-3 gap-3">{["VPS","Cloud VM","Kubernetes"].map(option=><div key={option} className="rounded-2xl border bg-[var(--card)] p-3 text-center"><Server className="mx-auto size-4 text-[var(--primary)]"/><div className="mt-2 text-xs font-black">{option}</div><div className="mt-1 text-[10px] text-[var(--muted-foreground)]">Equal candidate</div></div>)}</div><a href="#knowledge" className="mt-6 flex items-center justify-center gap-2 rounded-xl border bg-[var(--background)] px-4 py-3 text-sm font-black transition hover:bg-[var(--muted)]">Learn how decisions are made <ArrowRight className="size-4"/></a></div></div>}
function HowStep({icon:Icon,title,text,note,href,index,active,onActivate}:{icon:LucideIcon;title:string;text:string;note:string;href:string;index:number;active:boolean;onActivate:()=>void}){return <article className="how-step rounded-3xl border bg-[var(--background)] p-6"><button className="w-full text-left" onClick={onActivate} aria-expanded={active}><span className="grid size-12 place-items-center rounded-2xl bg-[var(--primary)]/10 text-[var(--primary)]"><Icon className="size-6"/></span><div className="mt-5 text-xs font-black uppercase tracking-[.14em] text-[var(--muted-foreground)]">0{index+1}</div><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{text}</p></button>{active&&<div className="how-popup mt-5 rounded-2xl border border-[var(--primary)]/30 bg-[var(--primary)]/10 p-4 text-sm leading-6"><strong className="block text-[var(--primary)]">System note</strong>{note}<Link className="mt-3 flex items-center gap-2 font-bold text-[var(--primary)]" href={href}>Try this path <ArrowRight className="size-4"/></Link></div>}</article>}
function Proof({text}:{text:string}){return <div className="flex items-center gap-2 text-sm"><CheckCircle2 className="size-4 shrink-0 text-[var(--primary)]"/>{text}</div>}
function Feature({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <Card className="card-hover h-full"><CardContent className="p-6"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--primary)]/10 text-[var(--primary)]"><Icon className="size-5"/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{text}</p></CardContent></Card>}
function Knowledge({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <article className="card-hover rounded-3xl border bg-[var(--background)] p-6"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--secondary)]/15 text-[var(--secondary)]"><Icon className="size-5"/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{text}</p></article>}
function Scan({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-[var(--card)] p-2"><div className="text-[9px] uppercase tracking-wide text-[var(--muted-foreground)]">{label}</div><div className="mt-1 text-[11px] font-black text-[var(--primary)]">{value}</div></div>}
function Footer(){return <footer className="relative overflow-hidden border-t bg-[var(--card)]"><div className="pointer-events-none absolute -right-24 -top-24 size-80 rounded-full bg-[var(--primary)]/10 blur-3xl"/><div className="relative mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="grid gap-10 md:grid-cols-[1.5fr_1fr_1fr]"><div><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-[var(--primary)] via-[var(--secondary)] to-[var(--accent)] text-[var(--primary-foreground)]"><Sparkles className="size-5"/></span><div className="text-xl font-black">AI Hosting Advisor</div></div><p className="mt-4 max-w-md text-sm leading-7 text-[var(--muted-foreground)]">A colorful knowledge space for understanding hosting, performance, testing and cost before making an infrastructure decision.</p><div className="mt-5 inline-flex rounded-full border bg-[var(--background)] px-4 py-2 text-xs font-black">Created by Dinushi Perera · 2026</div></div><FooterLinks title="Explore the guide" links={[["Home","#home"],["How it works","#how"],["Model prediction","#recommendation"],["Project knowledge","#knowledge"]]}/><div><div className="font-black">Advisor promise</div><p className="mt-4 text-sm leading-7 text-[var(--muted-foreground)]">No hidden hosting preference. The trained model selects the option; the rest of the workspace makes that choice understandable.</p><a href="#features" className="mt-4 inline-flex items-center gap-2 text-sm font-black text-[var(--primary)]">Explore capabilities <ArrowRight className="size-4"/></a></div></div><div className="mt-12 flex flex-col justify-between gap-3 border-t pt-5 text-xs text-[var(--muted-foreground)] sm:flex-row"><span>Evidence first. Clearer infrastructure choices.</span><span>Performance · Cost · Testing · Recommendation</span></div></div></footer>}
function FooterLinks({title,links}:{title:string;links:string[][]}){return <div><div className="font-black">{title}</div><div className="mt-4 grid gap-3 text-sm text-[var(--muted-foreground)]">{links.map(([label,href])=><Link className="w-fit transition hover:text-[var(--primary)]" key={label} href={href}>{label}</Link>)}</div></div>}
