import Link from "next/link";
import { ArrowRight, BrainCircuit, CheckCircle2, CircleDollarSign, Database, Download, Gauge, Globe2, History, Layers3, LockKeyhole, Rocket, Server, ShieldCheck, Sparkles, WandSparkles, type LucideIcon } from "lucide-react";
import { PublicNav } from "@/components/public/public-nav";
import { HeroVisual } from "@/components/public/hero-visual";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function Landing(){return <><PublicNav/><main id="main-content"><section className="relative overflow-hidden"><div className="absolute inset-0 hero-grid opacity-70"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 lg:grid-cols-2 lg:py-28"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border bg-[var(--card)] px-3 py-1.5 text-xs font-bold text-emerald-600 dark:text-emerald-300"><Sparkles className="size-3.5"/>AI + performance + workload + cost</div><h1 className="text-5xl font-black leading-[1.02] tracking-[-.04em] sm:text-6xl">Stop Guessing Your Hosting. <span className="gradient-text">Let AI Recommend What You Actually Need.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--muted-foreground)]">Analyse performance, estimate traffic needs, compare VPS, Cloud VM and Kubernetes, and receive a clear infrastructure recommendation in minutes.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="gradient" size="lg"><Link href="/register">Start Free Analysis<ArrowRight className="size-4"/></Link></Button><Button asChild variant="outline" size="lg"><Link href="/demo-showcase">View Demo</Link></Button></div><div className="mt-8 grid gap-2 text-sm text-[var(--muted-foreground)] sm:grid-cols-3"><Mini text="Explainable results"/><Mini text="Safe load-test planning"/><Mini text="Cost-aware guidance"/></div></div><HeroVisual/></div></section>
<section id="features" className="mx-auto max-w-7xl px-4 py-20"><div className="mx-auto max-w-2xl text-center"><div className="text-xs font-black uppercase tracking-[.18em] text-emerald-500">One decision-support workflow</div><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">From website signals to a practical hosting plan</h2><p className="mt-4 text-[var(--muted-foreground)]">Clear recommendations backed by confidence, evidence, assumptions and alternatives.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Feature icon={Globe2} title="Technology Detection" text="Surface likely frameworks, CMS, CDN and hosting signals with confidence and evidence."/><Feature icon={Gauge} title="Performance Auditing" text="Organize Lighthouse-style scores and Core Web Vitals into understandable actions."/><Feature icon={Layers3} title="Workload Estimation" text="Translate user, traffic, database and growth assumptions into rough capacity needs."/><Feature icon={BrainCircuit} title="AI Recommendation" text="Compare VPS, Cloud VM and Kubernetes with fit scores and explain why one wins."/><Feature icon={CircleDollarSign} title="Cost Explorer" text="Use ranges and assumptions instead of pretending cloud pricing is perfectly exact."/><Feature icon={ShieldCheck} title="Safe Load Testing" text="Generate authorized k6 plans only after ownership and impact acknowledgements."/></div></section>
<section id="how" className="border-y bg-[var(--card)]"><div className="mx-auto max-w-7xl px-4 py-20"><div className="grid gap-8 lg:grid-cols-3"><Mode icon={Globe2} title="1. Live Website" text="Enter a public URL, traffic assumptions and budget. Detect signals and audit performance." href="/analyze/live"/><Mode icon={Rocket} title="2. Planned Website" text="Describe architecture, traffic, workload and reliability before you deploy." href="/analyze/planned"/><Mode icon={WandSparkles} title="3. New Development Idea" text="Explain your idea in plain English and turn it into technology and hosting guidance." href="/analyze/new-idea"/></div></div></section>
<section id="compare" className="mx-auto max-w-7xl px-4 py-20"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="text-xs font-black uppercase tracking-[.18em] text-emerald-500">Explainable infrastructure choice</div><h2 className="mt-3 text-4xl font-black tracking-tight">Why Cloud VM? Why not VPS or Kubernetes?</h2><p className="mt-4 leading-7 text-[var(--muted-foreground)]">The recommendation page shows fit, cost range, scalability, operational complexity and the assumptions used. Low-confidence outcomes ask for missing information instead of pretending certainty.</p><div className="mt-6 grid gap-3"><Mini text="See recommendation confidence"/><Mini text="Edit assumptions and recalculate"/><Mini text="Compare alternatives side by side"/></div></div><div className="grid gap-4 sm:grid-cols-3"><CompareCard name="VPS" score="72/100" note="Good cost, limited scaling"/><CompareCard name="Cloud VM" score="88/100" note="Best balance" recommended/><CompareCard name="Kubernetes" score="61/100" note="Powerful, but too complex"/></div></div></section>
<section className="border-y bg-[var(--card)]"><div className="mx-auto max-w-7xl px-4 py-20"><div className="max-w-2xl"><div className="text-xs font-black uppercase tracking-[.18em] text-amber-600">Built for real decisions</div><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">Your work stays useful after the first recommendation</h2><p className="mt-4 text-[var(--muted-foreground)]">A practical workspace for teams and individuals who need repeatable evidence, accountable changes and usable outputs.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Reality icon={Database} title="Persistent workspace" text="Accounts, projects, assumptions and results are saved securely for future visits."/><Reality icon={History} title="Decision history" text="Revisit analysis runs, recommendations and important project changes over time."/><Reality icon={Download} title="Usable deliverables" text="Download or print a clear PDF report for reviews, approvals and planning."/><Reality icon={LockKeyhole} title="Safe by design" text="Protected sessions, scoped project access and authorization checks for load-test planning."/></div></div></section>
<section className="mx-auto max-w-5xl px-4 pb-24"><div className="overflow-hidden rounded-[32px] border bg-gradient-to-br from-emerald-600 via-emerald-600 to-amber-700 p-8 text-white shadow-2xl md:p-12"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><h2 className="text-3xl font-black">Ready to turn hosting uncertainty into a clear plan?</h2><p className="mt-3 max-w-2xl text-white/80">Start with a live website, planned project, or a new product idea.</p></div><Button asChild size="lg" className="bg-white text-emerald-700 hover:bg-white/90"><Link href="/register">Start analysis<ArrowRight className="size-4"/></Link></Button></div></div></section>
</main><footer className="border-t"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 md:grid-cols-4"><div><div className="font-black">AI Hosting Advisor</div><p className="mt-2 text-sm text-[var(--muted-foreground)]">Performance, infrastructure and cost decision support.</p></div>{['Product','Resources','Legal'].map((x)=><div key={x}><div className="font-bold">{x}</div><div className="mt-3 grid gap-2 text-sm text-[var(--muted-foreground)]"><span>Features</span><span>How it works</span></div></div>)}</div></footer></>}
function Mini({text}:{text:string}){return <div className="flex items-center gap-2"><CheckCircle2 className="size-4 text-green-500"/>{text}</div>}
function Feature({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <Card className="card-hover"><CardHeader><span className="mb-3 grid size-11 place-items-center rounded-2xl bg-emerald-500/10 text-emerald-500"><Icon className="size-5"/></span><CardTitle>{title}</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-[var(--muted-foreground)]">{text}</CardContent></Card>}
function Mode({icon:Icon,title,text,href}:{icon:LucideIcon;title:string;text:string;href:string}){return <Link href={href} className="group rounded-3xl border bg-[var(--background)] p-6 card-hover"><span className="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-emerald-500/15 to-amber-500/15 text-emerald-500"><Icon className="size-6"/></span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{text}</p><div className="mt-5 flex items-center gap-2 text-sm font-bold text-emerald-500">Explore<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></div></Link>}
function CompareCard({name,score,note,recommended}:{name:string;score:string;note:string;recommended?:boolean}){return <Card className={recommended?"border-emerald-500 shadow-lg shadow-emerald-500/10":""}><CardContent className="p-5 pt-5">{recommended&&<div className="mb-3 text-xs font-black uppercase tracking-wide text-emerald-500">Recommended</div>}<Server className="size-6 text-emerald-500"/><div className="mt-4 text-lg font-black">{name}</div><div className="mt-2 text-2xl font-black">{score}</div><div className="mt-2 text-xs leading-5 text-[var(--muted-foreground)]">{note}</div></CardContent></Card>}
function Reality({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <Card className="card-hover h-full"><CardContent className="p-5 pt-5"><span className="grid size-11 place-items-center rounded-2xl bg-amber-500/10 text-amber-600"><Icon className="size-5"/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{text}</p></CardContent></Card>}
