"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {motion} from "framer-motion";
import {Radar,RadarChart,PolarAngleAxis,PolarGrid,PolarRadiusAxis,RadialBar,RadialBarChart,ResponsiveContainer,Tooltip} from "recharts";
import {CheckCircle2,CircleSlash,ClipboardCheck,FlaskConical,Loader2,Play,ShieldCheck,XCircle} from "lucide-react";
import {toast} from "sonner";
import {PageHeader} from "@/components/shared/page-header";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Select} from "@/components/ui/input";
import {projectService} from "@/services/project-service";
import {testingService} from "@/services/testing-service";

const suites=[
 {key:"UT",name:"Unit Testing",proof:"Proves each saved input is valid and becomes a workload calculation."},
 {key:"IT",name:"Integration Testing",proof:"Proves your input, database records, trained models and recommendation connect."},
 {key:"ST",name:"System Testing",proof:"Proves the complete project workflow and its performance/load evidence."},
 {key:"UAT",name:"User Acceptance",proof:"Proves a user rated this project’s clarity, usefulness and trust."},
 {key:"ORT",name:"Operational Readiness",proof:"Proves k6, models and evidence storage are ready for this project."},
] as const;
type SuiteKey=typeof suites[number]["key"];
type Result={id:string;testType:string;testName:string;status:string;executedAt:string;details?:{expected?:string;actual?:string;plainLanguage?:string}};
type Summary={byType?:Record<string,{total:number;passed:number;failed:number;notRun:number}>;inputContext?:{projectName:string;mode:string;inputCompleteness:number;inputKeys:string[];workload?:{concurrentUsers:number;estimatedRps:number;peakRps:number}|null;recommendation?:string|null;performanceScore?:number|null;loadTests:number};results?:Result[]};

export default function Testing(){
 const client=useQueryClient();const projects=useQuery({queryKey:["projects"],queryFn:projectService.list});const [projectId,setProjectId]=useState("");
 useEffect(()=>{if(!projectId&&projects.data?.[0])setProjectId(projects.data[0].id)},[projectId,projects.data]);
 const summary=useQuery<Summary>({queryKey:["testing-summary",projectId],queryFn:()=>testingService.summary(projectId),enabled:Boolean(projectId)});
 const uat=useQuery({queryKey:["uat-summary",projectId],queryFn:()=>testingService.uatSummary(projectId),enabled:Boolean(projectId)});
 const run=useMutation({mutationFn:async(strategy:SuiteKey|"ALL")=>{if(!projectId)throw new Error("Choose a project first.");if(strategy!=="ALL")return testingService.run(strategy,projectId);const results=[];for(const suite of suites)results.push(await testingService.run(suite.key,projectId));return {strategy:"ALL",executed:results.reduce((n,item)=>n+(item.executed||0),0)}} ,onSuccess:data=>{client.invalidateQueries({queryKey:["testing-summary",projectId]});client.invalidateQueries({queryKey:["uat-summary",projectId]});toast.success(`${data.strategy} completed with ${data.executed} input-specific checks`)},onError:e=>toast.error(e instanceof Error?e.message:"Testing could not be completed")});
 const context=summary.data?.inputContext;const rows=summary.data?.results??[];
 const evidence=useMemo(()=>suites.map(s=>{const row=summary.data?.byType?.[s.key]??{total:0,passed:0,failed:0,notRun:0};return {strategy:s.key,verified:row.total?Math.round(row.passed/row.total*100):0,concerns:row.total?Math.round(row.failed/row.total*100):0,coverage:row.total?100:0}}),[summary.data]);
 const proofData=useMemo(()=>[{name:"Input",value:context?.inputCompleteness??0},{name:"Analysis",value:context?.workload&&context?.recommendation?100:0},{name:"Performance",value:context?.performanceScore??0},{name:"Load evidence",value:context?.loadTests?100:0},{name:"UAT",value:uat.data?.count?Math.round((uat.data.trust??0)*20):0}], [context,uat.data]);
 const total=evidence.reduce((n,item)=>n+item.verified,0);const conclusion=rows.length===0?"No input-specific evidence has been recorded yet. Run all five strategies to create a defensible conclusion.":evidence.some(item=>item.concerns>0)?"Some checks found input-specific concerns. Review the failed cases below before relying on this recommendation.":evidence.every(item=>item.coverage>0)?"The recorded checks support this project’s input-to-decision workflow. Missing UAT or load evidence remains clearly marked instead of assumed.":"The available evidence is positive, but one or more strategies still need to be run for this selected project.";
 if(projects.isLoading)return <div className="grid min-h-64 place-items-center"><Loader2 className="size-6 animate-spin"/></div>;
 return <div className="grid gap-6"><PageHeader eyebrow="Input-specific quality evidence" title="Project Testing" description="UT, IT, ST, UAT and ORT are generated only from the selected project’s saved inputs and evidence—not generic demo checks." actions={<Button asChild variant="outline"><Link href="/testing/model-evaluation">Model Evaluation</Link></Button>}/>
  <Card className="border-violet-500/25"><CardContent className="grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-end"><label className="grid gap-2 text-sm font-bold">Project being tested<Select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Choose a project</option>{projects.data?.map(project=><option key={project.id} value={project.id}>{project.name} · {project.mode}</option>)}</Select></label><Button size="lg" disabled={!projectId||run.isPending} onClick={()=>run.mutate("ALL")}>{run.isPending&&run.variables==="ALL"?<Loader2 className="size-4 animate-spin"/>:<ClipboardCheck className="size-4"/>}Run all input tests</Button></CardContent></Card>
  {projectId&&<><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Evidence label="Input completeness" value={`${context?.inputCompleteness??0}%`} hint="Saved user-provided fields"/><Evidence label="Concurrent users" value={context?.workload?.concurrentUsers??"Not calculated"} hint="From this project’s input"/><Evidence label="AI recommendation" value={context?.recommendation?.replaceAll("_"," ")??"Not ready"} hint="Trained-model decision"/><Evidence label="Performance score" value={context?.performanceScore??"Not measured"} hint="Project frontend evidence"/><Evidence label="Saved k6 tests" value={context?.loadTests??0} hint="Measured traffic evidence"/></section>
  <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Evidence profile</CardTitle><CardDescription>Radar view of verified and concern evidence for this project. This is not a model-accuracy chart.</CardDescription></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><RadarChart data={evidence} outerRadius="72%"><PolarGrid/><PolarAngleAxis dataKey="strategy"/><PolarRadiusAxis angle={30} domain={[0,100]}/><Radar name="Verified" dataKey="verified" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={.38}/><Radar name="Concerns" dataKey="concerns" stroke="#f97316" fill="#f97316" fillOpacity={.22}/><Tooltip/></RadarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>What this testing can prove</CardTitle><CardDescription>Coverage comes only from your selected project’s saved evidence.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-[.8fr_1.2fr]"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><RadialBarChart innerRadius="28%" outerRadius="92%" data={[{name:"Verified evidence",value:Math.round(total/5),fill:"#10b981"}]} startAngle={90} endAngle={-270}><RadialBar background dataKey="value" cornerRadius={10}/><Tooltip/></RadialBarChart></ResponsiveContainer></div><div className="grid content-center gap-2">{proofData.map(item=><div className="flex items-center justify-between rounded-xl bg-[var(--muted)] px-3 py-2 text-sm" key={item.name}><span>{item.name}</span><strong>{item.value}%</strong></div>)}</div></CardContent></Card></div>
  <Card className="border-cyan-500/25"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5 text-cyan-600"/>Conclusion for {context?.projectName??"this project"}</CardTitle><CardDescription>{conclusion}</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2">{context?.inputKeys?.map(key=><Badge key={key}>{key}</Badge>)}</div><p className="mt-4 text-sm text-[var(--muted-foreground)]">This testing proves the traceability of your inputs through calculations, database records, AI recommendation, available performance data, measured k6 evidence and project-specific feedback. It does not prove production capacity without an authorized load test and operational monitoring.</p></CardContent></Card>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{suites.map((suite,index)=>{const row=summary.data?.byType?.[suite.key]??{total:0,passed:0,failed:0,notRun:0};return <motion.div key={suite.key} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:index*.05}}><Card className="h-full"><CardHeader><div className="flex items-center justify-between"><FlaskConical className="size-5 text-violet-500"/><Badge>{row.total?`${row.total} TESTS`:"NOT RUN"}</Badge></div><CardTitle>{suite.key} · {suite.name}</CardTitle><CardDescription>{suite.proof}</CardDescription></CardHeader><CardContent><div className="grid grid-cols-3 gap-2 text-center"><Score icon={CheckCircle2} label="Pass" value={row.passed}/><Score icon={XCircle} label="Fail" value={row.failed}/><Score icon={CircleSlash} label="Pending" value={row.notRun}/></div><Button className="mt-4 w-full" disabled={run.isPending} onClick={()=>run.mutate(suite.key)}>{run.isPending&&run.variables===suite.key?<Loader2 className="size-4 animate-spin"/>:<Play className="size-4"/>}Run {suite.key}</Button></CardContent></Card></motion.div>})}</div>
  <Card><CardHeader><CardTitle>Input-specific test evidence</CardTitle><CardDescription>Expected result, actual project evidence, and why each check matters.</CardDescription></CardHeader><CardContent><div className="overflow-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Type</th><th>Test case</th><th>Status</th><th>Expected</th><th>Actual project result</th><th>What it proves</th></tr></thead><tbody>{rows.map(result=><tr className="border-b align-top" key={result.id}><td className="p-3 font-black">{result.testType}</td><td>{result.testName}</td><td><Badge>{result.status.replaceAll("_"," ")}</Badge></td><td>{result.details?.expected??"—"}</td><td>{result.details?.actual??"—"}</td><td className="max-w-xs">{result.details?.plainLanguage??"Stored project evidence."}</td></tr>)}</tbody></table></div></CardContent></Card></>}
 </div>}
function Evidence({label,value,hint}:{label:string;value:string|number;hint:string}){return <Card><CardContent className="p-4"><div className="text-xs text-[var(--muted-foreground)]">{label}</div><div className="mt-1 truncate text-xl font-black">{value}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">{hint}</div></CardContent></Card>}
function Score({icon:Icon,label,value}:{icon:typeof CheckCircle2;label:string;value:number}){return <div className="rounded-xl bg-[var(--muted)] p-2"><Icon className="mx-auto size-4"/><div className="mt-1 text-xs font-bold">{label}</div><div className="font-black">{value}</div></div>}
